getsentry/symbolic

- Cargo.toml
- common/src/errors.rs
- src/lib.rs
- symcache/Cargo.toml
- symcache/src/lib.rs
- symcache/src/read.rs
- symcache/src/types.rs
- symcache/src/utils.rs
This PR adds the initial symbol cache format.  A dwarf reader to write
it will be provided separately.
> Add Basic Symbol Cache Format

- cabi/include/symbolic.h
- cabi/src/symcache.rs
- py/symbolic/demangle.py
- py/symbolic/symcache.py
- py/tests/test_demangle.py
- symcache/src/cache.rs
Also renames `demangle_symbol` to `demangle_name` in python.
> ref(symcache): Rename Symbol to LineInfo

- common/src/types.rs
- debuginfo/src/object.rs
Needed for https://github.com/getsentry/sentry-cli/pull/245
> feat: Implement missing conversion traits on some types

- cabi/include/symbolic.h
- cabi/src/minidump.rs
- common/src/types.rs
- examples/minidump_stackwalk.rs
- minidump/cpp/data_structures.cpp
- minidump/cpp/data_structures.h
- minidump/src/processor.rs
- py/symbolic/minidump.py
- py/tests/test_minidump.py
> feat(minidump): Expose frame register values

- common/src/types.rs
@mitsuhiko the last commit is a bit controversial, not sure if we should merge it in.
> fix(common): Provide fallback types for unknown architectures

- common/src/byteview.rs
This handles the 1006 error code reported by windows for empty mmap files.
> fix: Fixed empty mmaps not being handled correctly on windows

- examples/minidump_stackwalk.rs
> feat(minidump): Improve stackwalking example

- Cargo.toml
- cabi/Cargo.lock
- cabi/Cargo.toml
- cabi/include/symbolic.h
- common/Cargo.toml
- debuginfo/Cargo.toml
- demangle/Cargo.toml
- minidump/Cargo.toml
- proguard/Cargo.toml
- sourcemap/Cargo.toml
- symcache/Cargo.toml
- unreal/Cargo.toml
> dep(proguard): Bump to 2.0.0

- symcache/src/writer.rs
Instead of inserting into the list of functions in order, this now sorts after all functions have been written. In order to be able to construct the `parent_offset` value, the original (unique) index is stored alongside the function address, which can be used to binary-search efficiently on the sorted list of functions.
This is not the most memory-efficient implementation, but in practice performance is close to the `symbolic 6.1.0`. For now, this will fix the most severe performance regressions.
> fix(symcache): Improve performance when writing out-of-order

- cabi/Cargo.lock
- demangle/Cargo.toml
Includes the recursion protection fixes
> feat: Bump cpp-demangle to 0.2.14

- .craft.yml
- .travis.yml
- Makefile
See https://github.com/getsentry/relay/pull/424
> build: Bump minimum macOS version to 10.13

- common/Cargo.toml
- common/src/types.rs
We need to send these across procspawn.
> feat(common): Support name serialization and deserialization

- debuginfo/Cargo.toml
- debuginfo/src/breakpad.rs
- debuginfo/tests/test_objects.rs
- minidump/Cargo.toml
- minidump/tests/test_cfi.rs
- minidump/tests/test_processor.rs
- symcache/Cargo.toml
- symcache/tests/test_cache.rs
- symcache/tests/test_writer.rs
- unreal/Cargo.toml
Insta was quite outdated and this should get it up to speed.
> test(insta): Upgrade insta to 0.15.0

- symbolic-unreal/src/context.rs
Found an unfixed lint in unreal.
> fix: New clippy lint on nightly

- .github/workflows/build.yml
- Makefile
- py/manylinux.sh
- py/setup.py
Manylinux has dropped support for 2.7, and so do we.
> build: Drop support for python 2.7

- symbolic-unwind/src/evaluator/parsing.rs
Among other things, this adds a `space_separated` parser combinator that will apply its child parser separated by zero or more spaces. I would've just used nom's `separated_list0`, but it doesn't work correctly if the separator parser (`multispace0` in this case) doesn't consume any input.
In general, parsers now don't consume whitespace before and after the thing they're supposed to parse.
> ref(unwind): Parsers consume less whitespace

- .github/workflows/ci.yml
- symbolic-debuginfo/src/pe.rs
- symbolic-debuginfo/src/sourcebundle.rs
Plus fix a few existing errors with the doc comments.
> Add CI to check doc comments

- symbolic-unwind/Cargo.toml
- symbolic-unwind/src/evaluator/mod.rs
- symbolic-unwind/src/evaluator/parsing.rs
- symbolic-unwind/src/evaluator/strategies.rs
This also necessitates some `Display` implementations (that should be there anyway) and a parser fix.
> test(unwind): Property based testing with proptest

- symbolic-common/src/path.rs
Nightly clippy prefers a for loop, probably fair enough.
> ref(clippy): Use for loop instead of while let

- symbolic-debuginfo/src/macho/compact.rs
With these fixes applied, a function with the following prolog:
```
0x100003260 <+0>:   pushq  %rbp
...
0x100003264 <+4>:   pushq  %r15
0x100003266 <+6>:   pushq  %r14
0x100003268 <+8>:   pushq  %r13
0x10000326a <+10>:  pushq  %r12
0x10000326c <+12>:  pushq  %rbx
```
And this raw unwind info:
```
function offset=0x00003260, encoding[4]=0x010558d1
```
It will now generate the following ASCII unwind info:
```
STACK CFI INIT 3260 140 .cfa: $rbp 16 + $rbp: .cfa -16 + ^ .ra: .cfa -8 + ^ $rbx: .cfa -56 + ^ $r12: .cfa -48 + ^ $r13: .cfa -40 + ^ $r14: .cfa -32 + ^ $r15: .cfa -24 + ^
```
CC @Gankra
> fix: Restore registers correctly for RBP-based compact unwind

- symbolic-debuginfo/Cargo.toml
- symbolic-debuginfo/benches/breakpad_parser.rs
- symbolic-minidump/benches/from_minidump.rs
- symbolic-unreal/Cargo.toml
- symbolic-unwind/Cargo.toml
This was:
* nom
* gimli
* bytes
Plus some clippy fixes.
> meta: Update dependencies

- py/symbolic/_compat.py
- symbolic-unwind/src/evaluator/mod.rs
> ref(clippy): Fix nightly clippy warnings

- symbolic-unreal/src/container.rs
- symbolic-unreal/tests/test_unreal_crash_parse.rs
fixes https://github.com/getsentry/symbolic/issues/476
> fix: Guard against unbounded memory allocation in UE4 parser

- symbolic-debuginfo/Cargo.toml
- symbolic-debuginfo/src/wasm/parser.rs
- symbolic-unreal/Cargo.toml
- symbolic-unreal/src/logs.rs
- symbolic-unreal/tests/test_unreal_crash_parse.rs
Well, this only goes halfway, since some dependencies still rely on chrono/time. The code changes necessary are a bit annoying though :-(
> fix: Try replacing chrono usage in symbolic-unreal

- symbolic-debuginfo/src/macho/mod.rs
We have seen a FatArch file in the wild for which the `offset + size` would wrap around, and thus cause a subslice panic.
> fix: Avoid slicing panic on FatArch overflow

- examples/symcache_debug/src/main.rs
- symbolic-debuginfo/src/macho/mod.rs
- symbolic-symcache/src/lib.rs
- symbolic-symcache/src/new/compat.rs
- symbolic-symcache/src/new/mod.rs
- symbolic-symcache/src/new/transform.rs
- symbolic-symcache/src/new/writer.rs
- symbolic-symcache/tests/test_writer.rs
> feat: Add BcSymbolMap transformation to symcache_debug

- examples/symcache_debug/Cargo.toml
- examples/symcache_debug/src/main.rs
- symbolic-il2cpp/Cargo.toml
- symbolic-il2cpp/src/binary/code_registration.rs
- symbolic-il2cpp/src/binary/dwarf.rs
- symbolic-il2cpp/src/binary/executable.rs
- symbolic-il2cpp/src/binary/mod.rs
- symbolic-il2cpp/src/lib.rs
- symbolic-il2cpp/src/line_mapping.rs
- symbolic-il2cpp/src/metadata/header.rs
- symbolic-il2cpp/src/metadata/image_definition.rs
- symbolic-il2cpp/src/metadata/method_definition.rs
- symbolic-il2cpp/src/metadata/mod.rs
- symbolic-il2cpp/src/metadata/type_definition.rs
- symbolic-il2cpp/src/utils.rs
- symbolic/Cargo.toml
- symbolic/src/lib.rs
This is not meant to be stable in any way.
> Experimental il2cpp code

- py/manylinux.sh
An attempt to fix https://github.com/getsentry/symbolic/runs/6522512319?check_suite_focus=true
> build: make manylinux update wheel

- py/manylinux.sh
Fixes the incorrect fix from #581.
> build: fix manylinux pip upgrade

- symbolic-debuginfo/src/breakpad.rs
This commit has been reviewed as part of #605. I'm attaching it as a separate PR so that it can be applied as an individual commit and doesn't get squashed with the rest of the work in #605.
Fixes #604.
This code is tested by tests/breakpad.rs test_macos_all() and others.
This lays the groundwork for correct processing of INLINE_ORIGIN records between FUNC records.
> Make BreakpadFunctionIterator do its own parsing.

- symbolic-debuginfo/src/function_builder.rs
> ref: Add some simple tests for FunctionBuilder

- symbolic-debuginfo/src/function_stack.rs
- symbolic-debuginfo/src/pdb.rs
- symbolic-debuginfo/tests/snapshots/test_objects__pdb_functions.snap
PDB inlinees and line records are being sorted now, and line records are being cleaned:
- zero-size line records are removed
- consecutive line records are merged
> ref: Simplify FunctionStack and PDB handling

- symbolic-cabi/Cargo.toml
- symbolic-symcache/Cargo.toml
Found using [`cargo-machete`](https://crates.io/crates/cargo-machete) :sunglasses: Let's see if CI confirms that this compiles fine...
> Remove unused dependencies

- .craft.yml
Because https://github.com/getsentry/symbolic/pull/692
> ci: Bump craft config to manylinux2014

- .github/workflows/stackaid.yml
This action will generate a stackaid.json file, listing the dependencies that Sentry wants to fund on StackAid. FYI, I'm one of the @stackaid founders helping @chadwhitacre setup Sentry's funding.
> Add action to generate stackaid.json

- symbolic-cfi/src/lib.rs
- symbolic-common/src/cell.rs
- symbolic-common/src/path.rs
- symbolic-debuginfo/src/dwarf.rs
- symbolic-debuginfo/src/elf.rs
- symbolic-ppdb/src/format/streams.rs
Mostly unneeded casts as well as other simplifications.
> ref: Pacify clippy

- examples/addr2line/src/main.rs
- examples/dump_cfi/src/main.rs
- examples/dump_sources/src/main.rs
- examples/minidump_stackwalk/src/main.rs
- examples/object_debug/src/main.rs
- examples/symcache_debug/src/main.rs
- examples/unreal_engine_crash/src/main.rs
- symbolic-cabi/src/core.rs
- symbolic-cabi/src/utils.rs
- symbolic-cfi/src/lib.rs
- symbolic-common/src/path.rs
- symbolic-common/src/types.rs
- symbolic-debuginfo/src/base.rs
- symbolic-debuginfo/src/dwarf.rs
- symbolic-debuginfo/src/elf.rs
- symbolic-debuginfo/src/macho/compact.rs
- symbolic-debuginfo/src/pe.rs
- symbolic-debuginfo/src/sourcebundle.rs
- symbolic-demangle/src/lib.rs
- symbolic-ppdb/tests/test_ppdb.rs
- symbolic-symcache/src/lookup.rs
> ref: Fix clippy lints

- .craft.yml
> auto publish to internal pypi on release

- .craft.yml
> ref: Update craft published artifacts

- symbolic-common/src/types.rs
This round includes deriving default.
> ref: Apply clippy lints

- README.md
See: https://github.com/getsentry/symbolic/pull/753#issuecomment-1412808676
> chore(readme): add il2cpp

- README.md
> Correct link to sentry-cabi/README.md

- symbolic-demangle/Cargo.toml
- symbolic-demangle/tests/test_cpp.rs
> Add demangling test for pathological symbol

- CHANGELOG.md
> Draft Changelog

- .craft.yml
- .github/workflows/build.yml
Well, looks like the 10.15 CI host/job does not start in any reasonable time, so lets update
> Update macos builder to latest

- symbolic-cabi/src/utils.rs
... when reading the source :)
> Fix super tiny typo

- CHANGELOG.md
> meta: Mention external contributor in changelog

- Cargo.lock
- examples/addr2line/Cargo.toml
- examples/addr2line/src/main.rs
- examples/debuginfo_debug/Cargo.toml
- examples/dump_cfi/Cargo.toml
- examples/dump_sources/Cargo.toml
- examples/minidump_stackwalk/Cargo.toml
- examples/object_debug/Cargo.toml
- examples/sourcemapcache_debug/Cargo.toml
- examples/symcache_debug/Cargo.toml
- examples/unreal_engine_crash/Cargo.toml
- symbolic-cabi/Cargo.toml
- symbolic-common/Cargo.toml
- symbolic-debuginfo/Cargo.toml
- symbolic-debuginfo/src/wasm/parser.rs
- symbolic-ppdb/Cargo.toml
- symbolic-sourcemapcache/Cargo.toml
- symbolic-symcache/Cargo.toml
> Update crate dependencies

- Cargo.lock
- symbolic-debuginfo/src/function_builder.rs
- symbolic-symcache/src/lookup.rs
> Update dependencies and fix clippy

- Cargo.lock
- symbolic-debuginfo/Cargo.toml
- symbolic-debuginfo/src/pe.rs
- symbolic-symcache/src/transform/mod.rs
- symbolic-unreal/Cargo.toml
> Cargo update and clippy fixes

- Cargo.lock
- scripts/bump-version
- symbolic-debuginfo/Cargo.toml
- symbolic-debuginfo/src/wasm/parser.rs
As always, includes some breaking changes from `wasmparser`.
> Do a `cargo update`

- symbolic-debuginfo/src/sourcebundle.rs
> docs(sourcebundle): Fix doc comment typo

- CHANGELOG.md
- Cargo.lock
This fixes an issue which prevents local compilation for me. We are unsure why CI is still passing, but in any case, this `cargo update` fixes the problem locally.
> build: Run `cargo update`

- .github/workflows/ci.yml
> build(ci): Build and test also on windows

- symbolic-demangle/build.rs
> ref(demangle): Improve build to use correct way to set c++ std

- CHANGELOG.md
> Add missing changelog for MSRV change
