getsentry/symbolic

.github/release.yml
.travis.yml
Makefile
py/manylinux.sh

build(wheels): Build wheels on Travis and prepare for releases

---

.editorconfig
cabi/include/symbolic.h
cabi/src/minidump.rs
minidump/cpp/data_definitions.h
minidump/cpp/data_structures.cpp
minidump/cpp/data_structures.h
minidump/src/processor.rs
py/symbolic/minidump.py
py/tests/test_minidump.py

Exposes all attributes except exploitability:
- requesting_thread: u32
- time_date_stamp: **u64** (was u32)
- crash_reason: String
- crash_address: u64
- assertion: String
- system_info:
- os: String
- os_short: String
- os_version: String
- cpu: String
- cpu_info: String
- cpu_count: u32
- *exploitability: enum* (not implemented)
Fixes #11

feat: Expose more minidump attributes

---

common/src/byteview.rs
common/tests/byteview.rs

This makes byteview not fail on empty files that are attempted to be
mmmapped in.

fix(common): Do not fail on empty mmap files

---

demangle/src/lib.rs
demangle/tests/basic.rs

The heuristic to detect `_ZN...E` as Rust symbols generates false positives for some symbols encountered in Electron stack traces, e.g.:
```
_ZN4base8internal7InvokerINS0_9BindStateIMN4mate19TrackableObjectBaseEFvvEJNS_7WeakPtrIS4_EEEEEFvvEE7RunImplIRKS6_RKNSt3__15tupleIJS8_EEEJLm0EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEE
```
Demangled:
```
void base::internal::Invoker<base::internal::BindState<void (mate::TrackableObjectBase::*)(), base::WeakPtr<mate::TrackableObjectBase> >, void ()>::RunImpl<void (mate::TrackableObjectBase::* const&)(), std::__1::tuple<base::WeakPtr<mate::TrackableObjectBase> > const&, 0ul>(void (mate::TrackableObjectBase::* const&&&)(), std::__1::tuple<base::WeakPtr<mate::TrackableObjectBase> > const&&&, base::IndexSequence<0ul>)
```
Also, the `try_demangle_cpp` …

fix: Correct demangling for ambiguous C++/Rust symbols

---

common/src/types.rs
demangle/src/lib.rs
demangle/tests/basic.rs

Objective C++ can contain both Objective C and C++ code, and thus contains
both mangled versions. When `Language::ObjCpp` is explicitly passed when
constructing the symbol, we need to use the heuristic do differenciate and
use the right demangler.
This fixes the remaining known issues for Electron crashes.

feat(demangle): Support symbols from Objective C++ code

---

cabi/include/symbolic.h
cabi/src/common.rs
cabi/src/debuginfo.rs
common/src/types.rs
debuginfo/src/breakpad.rs
debuginfo/src/dwarf.rs
debuginfo/src/lib.rs
debuginfo/src/object.rs
debuginfo/src/symbols.rs
minidump/src/cfi.rs
py/symbolic/debuginfo.py
symcache/src/breakpad.rs
symcache/src/dwarf.rs
symcache/src/writer.rs

This PR aims to clean up `FatObject` and `Object` handling by separating concerns and streamlining the behavior of different methods. More specifically:
- Symbol and dwarf handling have moved to separate traits. They can be used by importing `symbolic_debuginfo::{DwarfData, SymbolTable}`. The main reason for this is easier feature flagging and a clearer code structure. The C-ABI doesn't export any of these functions yet, but could use the traits, too.
- Most of Breakpad parsing has moved from `symcache` to `debuginfo`. This mostly concerns the low-level parser for records in ASCII symbols, implemented as iterator. Also, Breakpad module IDs (uuid+age) are represented by their own type `BreakpadId` which provides a convert back to UUID. For now, this simply discards the age -- but in future …

feat(debuginfo): Extend Object interface for debug information

---

debuginfo/src/object.rs
symcache/examples/symcache-debug.rs

- Adds a public `Objects` iterator
- Makes `FatObject::objects()` return an iterator by default
- Adapts the example in `symbolic_symcache`
Note that `FatObject::objects()` is not used in the CABI but only in Rust.
An iterator is therefore way more idiomatic and will save the vector allocation
in most cases. The example also shows, how to neatly collect the values into a
vector or any other data structure using `FromIterator for Result`.
`Objects::size_hint` and `Objects::count` are implemented for performance. The 
other methods are left the same, but if necessary we could also implement `nth`, 
`skip` etc...

ref(debuginfo): Make FatObjects iterable by default

---

debuginfo/src/lib.rs
debuginfo/src/symbols.rs
symcache/src/dwarf.rs
symcache/src/writer.rs

- Returns a `Symbol` struct instead of unnamed enum
- Properly abstracts MachO/ELF
- Adds missing documentation
- Took way to long to implement

ref(debuginfo): Refactor the symbols trait

---

cabi/include/symbolic.h
cabi/src/core.rs
cabi/src/utils.rs
py/symbolic/common.py
py/symbolic/exceptions.py
py/symbolic/utils.py

This enables backtraces even for regular errors which should help us
figure out where stuff breaks in production.

feat(py): Turn on backtraces even for regular errors

---

symcache/src/utils.rs
symcache/src/writer.rs

This intelligently strips down the path to fit into 255 characters which is
the limit with allotted in the file format for now.
We could in theory bump the segment to 16 bytes for the length but since the UI
also strips the paths down there is little value in doing that.

feat(symcache): Trim paths intelligently if they are too long for the symcache file

---

cabi/include/symbolic.h
cabi/src/minidump.rs
py/symbolic/minidump.py

Needed in sentry in case uploades are handled as `InMemoryUploadedFiles`.

feat(py): Support processing minidumps in memory

---

cabi/include/symbolic.h
cabi/src/minidump.rs
py/symbolic/minidump.py

This is needed so we can initialize more stack trace information in Sentry when creating the initial event. Otherwise, symbolication will leave the module name empty.
The code module is inlined directly into the frame, which substantially increases its size but makes handling it easier. An other option would have been to store a pointer into the `ProcessState.modules`.
Note that modules are **optional**. If a frame has no module associated, its memory is zeroed out. The python code checks this by looking at the `uuid`, `address` and `size` fields together.

feat(cabi): Expose frame's code modules to python

---

debuginfo/src/breakpad.rs
symcache/src/breakpad.rs

Adds support to parse `INFO` records in Breakpad ASCII symbols. Also, breakpad to symcache conversion silently swallowed errors.

fix(debuginfo): Parse INFO records in breakpad symbols

---

cabi/include/symbolic.h
cabi/src/minidump.rs
minidump/Cargo.toml
minidump/src/lib.rs
minidump/src/processor.rs
py/symbolic/minidump.py
py/tests/test_minidump.py

Splits the `os_version` string from minidump into the version and build information. 
On Linux, the version number is often times `0.0.0` while the build contains information obtained via `uname -srvmo`. This includes the architecture, linux kernel version and build version of the distribution. For now, the `uname -r` (kernel release) is used as `version` and `uname -v` (kernel version) as build.
Note that `uname -r` contains version numbers like "4.10.0-42-generic". This currently breaks in Sentry but will be fixed in the PR introducing Linux symbolication support.

feat(minidump): Separate version and build number

---

symcache/src/cache.rs

Most of the CABI functions had this already, but the symcache convenience functions were missing it.

fix(symcache): Demangle with language explicitly

---

py/tests/test_crashprobe.py
symcache/src/dwarf.rs
symcache/src/writer.rs

**NOTE**: This currently breaks `py/tests/test_crashprobe.py:test_swift`!
Seems like line number programs only contain entries for actual instructions. Therefore, we have to fall back to reading `DW_AT_call_file` and `DW_AT_call_line` to get the call site of an inlined function call. 
I tried to test for performance regressions but it seems about the same. @mitsuhiko if you have some test files it would be great if you could double-check.
Example program to trigger this behavior (C++):
```cpp
namespace {
void crash() {
volatile int *i = reinterpret_cast<int *>(0x45);
*i = 5;  // crash!
}
void start() {
// This function will be fully inlined with -O3 and has no "own" 
// instructions. Yet, a stacktrace should show the line below:
crash(); 
}
}
int main(int argc, char **argv) {
start();  // …
```

fix(symcache): Correctly infer call site for inlined functions

---

py/manylinux.sh

Besides, we're not really interested in `yum` output anyway

ci: Fix random Travis failures related to blocking stdout

---

cabi/include/symbolic.h
cabi/src/symcache.rs
examples/minidump_stackwalk.rs
py/symbolic/symcache.py
symcache/src/cache.rs

This PR exposes the instruction address at which a source line starts via `LineInfo`. 
While the docs of `LineInfo::sym_addr()` suggested this, it is actually returning the first instruction of the function. Instead, a new function `LineInfo::line_addr()` now returns this value. This change was made in commit 36f0759 (_feat(symcache): Add line address to LineInfo_).
The other commits expose this change to python or improve the general documentation of the `SymCache`.

fix(symcache): Add line address and improve code docs

---

cabi/include/symbolic.h
cabi/src/common.rs
cabi/src/minidump.rs
cabi/src/symcache.rs
common/src/types.rs
examples/minidump_stackwalk.rs
minidump/cpp/data_structures.cpp
minidump/cpp/data_structures.h
minidump/src/processor.rs
py/symbolic/minidump.py
py/tests/test_minidump.py
symcache/src/heuristics.rs

This PR tries to expose the original return addresses from stack frames without Breakpad's instruction heuristics. It allows us to apply our own heuristics defined in `symcache/heuristics` from Sentry. On the bottom line, Sentry no longer has to distinguish between minidump stacktraces and KSCrash stacktraces to perform correct symbolication.
The first issue was to obtain the actual return address from the process state. Breakpad defines the following interface for stack frames:
```
struct StackFrame {
// Return the actual return address, as saved on the stack or in a
// register. See the comments for 'instruction', below, for details.
virtual uint64_t ReturnAddress() const { return instruction; }
// The program counter location as an absolute virtual address.
// - [Except for the first …
```

fix(minidump): Use original return addresses

---

debuginfo/Cargo.toml
debuginfo/src/dwarf.rs
debuginfo/src/elf.rs
debuginfo/src/lib.rs
debuginfo/src/mach.rs
debuginfo/src/object.rs

This PR fixes some issues with ELF processing and refactors some format-specific code into its own helper modules.
This algorithm computes a UUID for the ELF binary. The previous way to use `e_ident` in the ELF header is simply wrong, as `e_ident` is no identifier by any means but rather a collection of magic and flags. For obvious reasons, we try to closely resemble what Breakpad is doing:
1. Determine the build identifier:
1. First, try to locate a `NT_GNU_BUILD_ID` in one of the `PT_NOTE` program header entries
2. Otherwise, locate the above note in the contents of the `".note.gnu.build-id"` section
3. If the above does not work, take the entire `".text"` section (the program code) and XOR it into a 16 byte buffer
2. Strip or extend the buffer obtained above to exactly 16 bytes
3. …

fix(debuginfo): Compute correct UUID for ELF binaries

---

cabi/Cargo.toml
cabi/src/core.rs
cabi/src/lib.rs
cabi/src/utils.rs

Backports some work conducted on the cabi crate: Fixes backtraces for panics and improves rendering of backtraces. In both cases, `error_chain` is used to create an error including a backtrace and stored in `LAST_ERROR`.
**Panic Backtrace**
```
Panic: panic: thread 'unnamed' panicked with 'this should panic' at /Users/jauer/Coding/symbolic/common/src/byteview.rs:68
stacktrace:
0x10799eff9 std::panicking::try::do_call::hce186e5269aa29d7 (.llvm.F576D645)
0x1079b7cc0 symbolic::utils::landingpad::h9e547e03fcd0c5e5
0x1079a9e54 symbolic_symcache_from_path
0x7fff5088cf63 ffi_call_unix64
0x7fff5088d77b ffi_call
[205 python frames omitted]
```
**Error Backtrace**
```
Io: No such file or directory (os error 2)
stacktrace:
0x101a66a55 symbolic_common::byteview::ByteView::from_path::h86257803c7e93187 …
```

fix(cabi): Report correct backtraces for panics

---

debuginfo/src/breakpad.rs
debuginfo/src/object.rs
minidump/Cargo.toml
minidump/src/lib.rs
minidump/src/processor.rs

This PR removes duplicate code for handling Breakpad identifiers and also allows all valid Breakpad debug identifers of up to 40 characters. Previously, only 33 characters were allowed. Last, `Display` has been update to render the `age` field in lowercase hex instead of uppercase.
The new common type is called `ObjectId`. This PR is meant as a first step to transition to the new ID system. However, since the concept has not been finalized, it cannot be used in place of UUIDs to identify `Object`s yet.
In the end, we might need to transition back to a separate `ObjectId` and `CodeModuleId`, but for now it's easier this way. In the meanwhile, the type is aliased in `symbolic_minidump`.
**Note**: This is a breaking change to the public API (`symbolic_debuginfo::BreakpadId` -> …

ref: Fix and streamline object identifiers

---

cabi/include/symbolic.h
cabi/src/core.rs
cabi/src/debuginfo.rs
cabi/src/minidump.rs
cabi/src/proguard.rs
cabi/src/symcache.rs
debuginfo/src/breakpad.rs
debuginfo/src/elf.rs
debuginfo/src/mach.rs
debuginfo/src/object.rs
py/symbolic/debuginfo.py

This PR adds the previously introduced `ObjectId` type (UUID + age) to `Objects` and exposes it via the C-ABI to Python.
Also performs some cleanup in the C-ABI to reduce duplicated code to convert `Uuid` into `SymbolicUuid`.
Since the ObjectId proposal still has not been finalized, the `ObjectId` type is still subject to change and will not be used for the object lookup in Sentry.

feat(debuginfo): Use the new ObjectId for objects

---

debuginfo/src/symbols.rs

This was definitely broken in previous releases and also in `sentry-cli` since we migrated to `symbolic`. Since our symbol iterator strips the first `"_"` in the symbol name, the regular expression never matched.
Also adding a trailing `"_"`, as hidden symbols seem to have this. @mitsuhiko can you confirm?

fix(debuginfo): Match Apple's hidden symbols correctly

---

py/setup.py

The RTLD_NODELETE flag is not supported by the dlopen implementation on OpenBSD. Because of this, we need to exclude this flag from the installation as milksnake will throw an exception when trying to install.

make setup.py work in OpenBSD

---

common/Cargo.toml
common/src/lib.rs
common/src/types.rs
debuginfo/Cargo.toml
debuginfo/src/id.rs
debuginfo/src/lib.rs
minidump/Cargo.toml
minidump/src/lib.rs
minidump/src/processor.rs

This primarily allows to derive `Serialize` and `Serialize` for types containing these types, as required by Sentry CLI.

feat: Implement serde traits for common types

---

py/symbolic/debuginfo.py
py/tests/test_debug.py

`encode_str` wasn't imported and there were no tests.

fix(py): Fix id_from_breakpad implementation

---

.travis.yml
cabi/src/minidump.rs
common/src/types.rs
examples/minidump_stackwalk.rs
minidump/src/processor.rs
minidump/tests/snapshots/process_state_linux.txt
minidump/tests/snapshots/process_state_macos.txt
minidump/tests/snapshots/process_state_windows.txt
minidump/tests/snapshots/referenced_modules_linux.txt
minidump/tests/snapshots/referenced_modules_macos.txt
minidump/tests/snapshots/referenced_modules_windows.txt
py/symbolic/debuginfo.py
py/symbolic/minidump.py
py/tests/test_debug.py
symcache/src/types.rs

Breakpad can return `""` as `debug_identifier` in certain instances. We make the `id()` return value optional to prevent a `panic`:
```rust
pub fn id(&self) -> Option<CodeModuleId> {
CodeModuleId::from_str(&self.debug_identifier()).ok()
}
```
Python returns `None` in this case. Minor fixes in sentry needed to support this. 
Fixes [SENTRY-5P5](https://sentry.io/sentry/sentry/issues/429475080)

ref(minidump): Make CodeModuleIds optional

---

Cargo.toml
cabi/Cargo.toml
src/lib.rs

Introduces features for every top-level crate. Since `common` is always needed, there is no feature for that. In additon, each feature might have dependencies on other features:
- `debuginfo`: none
- `demangle`: none
- `minidump`: `debuginfo`
- `proguard`: none
- `sourcemap`: none
- `symcache`: `debuginfo`, `demangle`
- `with_serde`: activates inside `common`, `debuginfo` and `minidump`

feat: Create features for every top-level crate

---

cabi/src/minidump.rs
minidump/cpp/data_structures.cpp
minidump/cpp/data_structures.h
minidump/src/processor.rs
minidump/tests/snapshots/process_state_linux.txt
minidump/tests/snapshots/process_state_macos.txt
minidump/tests/snapshots/process_state_windows.txt

This PR exposes all loaded code modules in python's `ProcessState.modules` function as opposed to only referenced ones. This will allow us to do proper CFI walking in Sentry.

feat(minidump): Expose all loaded modules to python

---

cabi/src/core.rs
examples/object_debug.rs

This bug was introduced after upgrading to a recent `failure` version (see https://github.com/rust-lang-nursery/failure/pull/252)

fix(cabi): Map errors correctly after failure upgrade

---

cabi/Cargo.lock
scripts/bump-version

At @jan-auer's request, this explicitly pins dependencies of "cabi".
Cargo.toml/.lock of "cabi" should be also properly updated while before releases.

fix: Add Cargo.lock for cabi

---

cabi/Cargo.lock
demangle/Cargo.toml
demangle/src/lib.rs
demangle/tests/cpp.rs
demangle/tests/msvc.rs

Adds support for demangling MSVC symbols. This will be needed to support PDBs.
Ref #72

feat: Add MSVC demangling support

---

cabi/include/symbolic.h
cabi/src/debuginfo.rs
debuginfo/Cargo.toml
debuginfo/src/features.rs
debuginfo/src/lib.rs
debuginfo/src/symbols.rs
debuginfo/tests/test_features.rs
py/symbolic/debuginfo.py
py/tests/test_debug.py

This PR adds a function `Object::features()` that returns the different pieces of information contained in an object file, such as unwind info and debug info. Features are an abstract concept that can be used to determine whether an object file is suitable input to certain operations, such as symbolication or stack walking.
The list of features is kept to a minimum for now, but can be extended with more entries later depending on relevant use cases.
Based on https://github.com/getsentry/symbolic/pull/90

feat(debuginfo): Extract object features and expose them to python

---

cabi/include/symbolic.h
cabi/src/core.rs
cabi/src/minidump.rs
cabi/src/symcache.rs
examples/minidump_stackwalk.rs
minidump/src/cfi.rs
minidump/src/processor.rs
py/symbolic/debuginfo.py
py/symbolic/minidump.py
py/symbolic/symcache.py
py/tests/test_minidump.py
symcache/src/cache.rs

Adds an explicit type `CfiCache`. It is versioned similar to `SymCache`, can be created from objects and can be written and read from files. 
Strictly speaking, this is a breaking change. Since we never used CfiCaches in the past, however, there is no need to perform a major bump.

feat: Add an explicit type for CFI caches

---

.gitmodules
py/tests/test_minidump.py

Updates the breakpad submodule to our fork with a small patch. Also makes the submodule shallow which should speed up cloning and the initial build.

 build: Switch to breakpad fork

---

debuginfo/src/lib.rs
py/symbolic/debuginfo.py
py/tests/test_debug.py

Fixes two major issues in object lookup: `ObjectLookup.find_object(instruction_addr)`
- We missed modules when we passed the image_addr as instruction_addr
- If the address passed in was a hex string, we skipped the symbol

fix(py): Fix object lookup by address

---

symcache/src/dwarf.rs

This fixes the _"could not find root function"_ error for some debug symbols. We did not take into account that LTO might remove code for a function that leaves behind a surrogate DIE with inlined children that might have ranges attached. In that case, we tried to attach them to a non-existing parent function.

fix(symcache): Skip inlined children of dead code DIEs

---

cabi/Cargo.lock
debuginfo/Cargo.toml
debuginfo/src/dwarf.rs
debuginfo/src/elf.rs
debuginfo/src/features.rs
debuginfo/src/lib.rs
debuginfo/src/mach.rs
symcache/Cargo.toml
symcache/src/breakpad.rs
symcache/src/dwarf.rs
symcache/src/error.rs
symcache/src/lib.rs
symcache/src/writer.rs
unreal/Cargo.toml

The changes in `symcache/dwarf.rs` got a little out of hand since gimli's structs only operate on slices but we need to hold on to the buffers at the same time.
The symbols still don't fully process, but this might be unrelated.

feat(debuginfo): Support zlib compressed ELF sections

---

minidump/cpp/data_structures.cpp

It appears that breakpad actually does not set the modules pointer if there are no modules in a minidump. This lead to a null dereference segfault.
I did a quick scan over other information that we read, but this is the only unchecked case where a null value is possible.

fix(minidump): Check for missing modules list

---

py/symbolic/debuginfo.py

Strictly speaking, `image_addr` and `image_size` are required, but it's better to be lenient here and filter the images in Sentry before passing them in.

fix(py): Do not throw on missing object attributes

---

debuginfo/src/breakpad.rs

Adds a workaround so that we do not reject Breakpad symbols with negative line numbers. 
Negative line records are technically invalid. However, they seem to occur when `dump_syms` is not able to evaluate the DWARF line program correctly. This happens occasionally for user symbols, e.g. [Electron](https://github.com/electron/electron/releases/download/v3.0.13/electron-v3.0.13-linux-x64-symbols.zip).
To handle this case more gracefully, we now just reinterpret line numbers as `i32` and cast them over to `u32`. Breakpad's `dump_syms` internally uses `int` for line numbers, so the value should match. SymCaches will truncate this to `u16::MAX`.
Breakpad's own symbol parser also discards such records as invalid: https://github.com/google/breakpad/blob/79ba6a494fb2097b39f76fe6a4b4b4f407e32a02/sr …

fix(debuginfo): Workaround for negative Breakpad line numbers

---

cabi/include/symbolic.h
cabi/src/minidump.rs
minidump/src/processor.rs
minidump/tests/snapshots/test_processor__process_state_macos.snap
minidump/tests/snapshots/test_processor__referenced_modules_macos.snap
py/symbolic/minidump.py
py/tests/test_minidump.py

This exposes the code identifier and debug file name to python. The new interface now is:
- `code_id`: Implementation defined code identifier, if any
- `code_file` (alias `name`): Full path to the code file
- `debug_id` (alias `id`): Contains the normalized debug identifier (in Breakpad format)
- `debug_file`: Name of the debug file, if any
For backwards compatibility, the old attributes have been retained but are marked as deprecated.

feat(py): Expose minidump module's code_id and debug_file

---

py/symbolic/debuginfo.py
py/tests/test_debug.py

This prepares a schema change in Sentry regarding native debug images. The `name` attribute on `ObjectRef` was overlooked in the 6.0.0 refactor (see #127). For now, it remains for backwards compatibility as an alias to `code_file`.
**Renamed properties:**
- `id` -> `debug_id`
- `name` -> `code_file`
**New optional properties:**
- `code_id`
- `debug_file`

feat(py): Support updated debug image schema in ObjectLookup

---

cabi/Cargo.lock
cabi/c-tests/object.c
common/Cargo.toml
debuginfo/src/breakpad.rs
debuginfo/src/elf.rs
debuginfo/src/macho.rs
debuginfo/src/pe.rs
debuginfo/tests/test_objects.rs

Updates to the latest version of `debugid` which includes the updated `CodeId` type.

ref: Switch to updated CodeId signature

---

common/src/byteview.rs

This is useful for opening byteviews from unnamed tempfiles (files that have no hardlink).

feat: Ability to open ByteView from open filehandle

---

py/symbolic/minidump.py
py/symbolic/unreal.py
py/symbolic/utils.py
py/tests/test_unreal.py

Sentry wants to know the size of a few things before it consumes data from the
stream.  Since we can provide the size here this now adds this attribute which
has the same name (`size`) as we use in Sentry proper (and Django).

feat(py): Added size attribute to streams

---

debuginfo/src/base.rs
debuginfo/src/object.rs
debuginfo/src/pe.rs
debuginfo/tests/test_objects.rs

Since PE files are the definite source of what a PDB is suppose to be called
this exposes this information from the object.  This is only implemented for PE
files as it does not make much sense in other contexts.

feat(debuginfo): Expose the PDB filename from PEs

---

cabi/Cargo.lock
common/Cargo.toml
debuginfo/src/breakpad.rs
debuginfo/src/elf.rs
debuginfo/src/macho.rs
debuginfo/src/pe.rs

`debugid` 0.5.2 is released already.

ref(common): Revert to string-based CodeId

---

debuginfo/src/breakpad.pest
debuginfo/src/breakpad.rs

This allows debug identifiers that do not contain an age (i.e. length of 32 characters). To my understanding, this should never be generated by `dump_syms`, yet it happens in production. As `DebugId` can handle this, there is no harm in allowing such identifiers.

feat(breakpad): Support debug identifiers without age

---

minidump/src/processor.rs

Returns a `ProcessState` even if the minidump contains no thread list. 
The thread list is retrieved as the last processing step, immediately before symbolication. As such, system information and exception information might still be available. It's better to return this partial process state than fully bailing out.
https://github.com/google/breakpad/blob/d930308bbbfa089a63df67c4f78065604494d39d/src/processor/minidump_processor.cc#L156-L160

feat(minidump): Return ProcessStates for minidumps without threads

---

minidump/cpp/processor.cpp
minidump/src/processor.rs

Fix for #144. Also fixes a memory leak if the minidump cannot be opened.
Please review carefully. This is unfortunately hard to test as I cannot reproduce this case and we stopped to store failing minidumps.

fix(minidump): Return process states for minidumps without threads

---

debuginfo/src/elf.rs
symcache/src/cache.rs
symcache/src/format.rs

This reverts #120. As it turns out, the first `PT_LOAD` segment is always the correct one to use as load address.
This goes along the lines of this change: https://github.com/google/breakpad/commit/3444ed7cf1118f3f288bc6941c8e726f732ad8c6

fix(debuginfo): Consider all program headers for ELF

---

debuginfo/Cargo.toml
debuginfo/src/pdb.rs

See https://github.com/willglynn/pdb/pull/44

fix(debuginfo): Prefer a PDB's DebugInfo age

---

common/src/types.rs

Adds architecture aliases for parsing the "Code Type" of apple crash reports.
See: https://developer.apple.com/library/archive/technotes/tn2151/_index.html#//apple_ref/doc/uid/DTS40008184-CH1-CRASH_HEADER

feat(common): Add architecture aliases for apple crash reports

---

debuginfo/src/base.rs
symcache/src/format.rs
symcache/src/writer.rs
symcache/tests/snapshots/test_writer__functions_linux.snap
symcache/tests/snapshots/test_writer__functions_macos.snap
symcache/tests/test_writer.rs

This fixes three conditions:
1. It allows functions with more than 65k line records by splitting the address range and allowing multiple function records.
2. It splits functions with a code length of more than 65k bytes (using the same mechanism)
3. It no longer emits any function records without line records.
4. **bugfix**: do not skip to write line records between sibling inlined functions
The bugfix is achieved by creating an isolated line cache for every layer when recursing into inlinees. Since line records might be missing from existing symcaches, the **symcache version was bumped**.

fix(symcache): Allow functions with more than 65k lines

---

minidump/src/cfi.rs
minidump/tests/snapshots/test_cfi__cfi_elf.snap
py/tests/res/minidump/crash_linux.sym

Preliminary fix for recursions in stackwalking with CFI on Linux. This no longer emits a default rule for the `.ra` register. The rule was initially introduced to create parity with Breakpad, but turns out to be plain wrong.
There will be a more elaborate fix once `gimli` has been updated.

fix(minidump): Do not emit default CFI for the .ra register

---

py/symbolic/common.py
py/symbolic/debuginfo.py
py/tests/test_minidump.py

Fixed some regression in tests that caused them not to work on 3.x and removed a pointless six
dependency which accidentally snuck in.

fix: Make tests pass on 3.x again and remove six dependency

---

demangle/build.rs
minidump/build.rs

For "-std=c++11" it is just to disable warnings and for "-Wno-tautological-constant-out-of-range-compare" it's mandatory to be able to compile.

Fix compilation unwder Windows when using MSVC

---

debuginfo/src/sourcebundle.rs

This can be used by tools to prevent sources to be added in certain circumstances.

feat(sourcebundle): Added callback to skip over files

---

debuginfo/src/macho.rs
debuginfo/src/object.rs

This fixes a mis detection of class files as macho fat files by using a
heuristic to tell the files apart based on on number of macho embedded
architectures vs class file versions.
Additionally it changes the slicing code to manual slicing which prevents
us panicking if we accidentally read bad ranges from a macho file.  This
happend commonly when we mis-characterized class files as macho fat files.

fix: Harden macho multi arch parsing code.

---

unreal/src/context.rs

Fixed typo changed `Unreal4ContextRuntimeProperties::misc_primary_cpu_brand` to `misc_primary_gpu_brand`.

fix(unreal): Fix typo in ContextRuntimeProperties

---

unreal/src/logs.rs

The first line is a header and should not end up as a log entry.

fix(unreal): Remove the first line from the Unreal Log

---

.travis.yml
Makefile
cabi/include/symbolic.h
cabi/src/core.rs
py/symbolic/common.py
py/symbolic/debuginfo.py
py/symbolic/demangle.py
py/symbolic/minidump.py
py/symbolic/proguard.py
py/symbolic/sourcemap.py
py/symbolic/symcache.py
py/symbolic/unreal.py
py/symbolic/utils.py

We did not consistently call `free=True` on strings returned from the C-ABI. This PR updates docs and adds the flags where appropriate.

fix(cabi): Consistently free strings obtained from the C-ABI

---

.travis.yml

I'm targetting Python 3.6 support for sentry, so this makes linux-python test against python3.6 instead of the default 3.5. If 3.5 support is desired I can just add another matrix job.
Note that mac-python appears to be 3.7.5, so it should just work.

test(python): test against python3.6

---

debuginfo/src/elf.rs

This fixes decompression of `.zdebug*` GNU sections.

fix(debuginfo): Decompress GNU compressed debug sections correctly

---

debuginfo/src/dwarf.rs
debuginfo/src/macho.rs

I am using `symbolic_debuginfo` in a [symbolicator](https://github.com/mozilla/fix-stacks) used for stack traces produced by Firefox.
On Mac, we don't build dSYMs by default because doing so is slow. So I want to emulate `atos`, which is able to read debuginfo from a binary by consulting the binary's symbol table and then reading debug info from the object files and archive files mentioned.
I have this working, but it requires a couple of small changes to `symbolic_debuginfo`, due to slight differences between `.o` files and executables/libraries.

fix(debuginfo): Improve `.o` handling on MachO (#173)

---

debuginfo/src/base.rs
debuginfo/src/dwarf.rs

It aims to fix: https://github.com/getsentry/symbolic/issues/195

[debuginfo] No error in functions iterator on name errors

---

src/lib.rs

In rust 2018 edition re-exports of dependent crates are not
automatically inlined.  So we need to give this a hint.

docs: Inline docs from sub-crates

---

.travis.yml

Cargo caches keep growing and eventually are slower to download than just rebuilding. Also, we used to test the python implementation by compiling in release mode, which is unnecessarily slow.

ci(travis): Disable cargo caches and test python in debug

---

common/Cargo.toml
common/src/path.rs
debuginfo/Cargo.toml
debuginfo/tests/test_objects.rs
examples/dump_cfi.rs
examples/dump_sources.rs
examples/object_debug.rs
examples/symcache_debug.rs
minidump/Cargo.toml
minidump/tests/test_cfi.rs
minidump/tests/test_processor.rs
symcache/Cargo.toml
symcache/benches/bench_writer.rs
symcache/tests/test_cache.rs
symcache/tests/test_compat.rs
symcache/tests/test_writer.rs
testutils/Cargo.toml
testutils/fixtures/macos/crash.dSYM/Contents/Resources/DWARF/invalid
testutils/src/lib.rs
unreal/Cargo.toml
unreal/tests/test_unreal_crash_parse.rs

Implements utilities for dealing with `dSYM` folder structures. They can check for a dSYM folder structure, resolve the dSYM parent from a deep path, and resolve the deep path from the parent folder.
`sentry-cli` partially implements this logic already, so we can reduce some duplicate code here. Also, the examples used to require that one declares the full path to a dSYM file, but this is just unnecessary.

feat(common): Add Path utilities for dSYM structures

---

debuginfo/src/elf.rs
debuginfo/tests/snapshots/test_objects__elf_functions.snap
debuginfo/tests/test_objects.rs
symcache/tests/snapshots/test_writer__functions_linux.snap
symcache/tests/test_writer.rs

The test `test_elf_functions` is failing because of this change:
```
──────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
117 ⋮ 
118 ⋮     > 0x1d72: crash (0xb)
119 ⋮       0x1d72: main.cpp:23 (../linux)
120 ⋮ 
121 ⋮-> 0x1ec0: callback (0x3b)
122 ⋮+> 0x1ec0: _ZN12_GLOBAL__N_18callbackERKN15google_breakpad18MinidumpDescriptorEPvb (0x3b)
123 ⋮   0x1ec0: main.cpp:9 (../linux)
124 ⋮   0x1ec2: main.cpp:8 (../linux)
125 ⋮   0x1ec5: main.cpp:9 (../linux)
126 ⋮   0x1ec7: main.cpp:15 (../linux)
127 ⋮   0x1eda: main.cpp:19 (../linux)
134 ⋮ 
135 ⋮     > 0x1ee0: printf (0x17)
136 ⋮       0x1ee0: stdio2.h:104 (/usr/include/x86_64-linux-gnu/bits)
137 ⋮ 
138 ⋮-> 0x1f00: _ZN15google_breakpad18MinidumpDescriptorD2Ev (0x32) …
```

fix(debuginfo): don't skip symbols in executable section with NOBITS type

---

debuginfo/src/dwarf.rs
debuginfo/src/elf.rs
debuginfo/src/macho.rs

Fixes an issue that indirectly lead to _"inline parent offset too large for symcache file format"_ errors by reintroducing checks for functions with a `DW_AT_low_pc` of `0`.
In regular shared objects or executables, such functions have been eliminated by the linker. As the primary use case of this library is to symbolicate stack traces, yielding such functions from the function iterator is not desirable. Also, the virtual address of the functions is no longer valid and implicitly overlaps with other eliminated functions. At least in the default behavior, they should not be included.
Removing the checks introduced a 10% performance regression on large ELF symbols. I did not notice this on my initial tests, since I missed the fact that this case is only triggered by the GNU linker. If it …

fix(debuginfo): Skip eliminated functions in linked objects

---

common/src/path.rs

Fixes panics when joining or normalizing paths when they contain multi-byte unicode characters. Along with this, some common code is refactored to reduce code duplication.
The behavior of some of these functions is suboptimal, particularly `join_path` and `shorten_path`. The next step could be to refactor those methods internally to fix the known broken tests and odd behavior. Next, we could create a proper library for a unified `Path` type.

fix(common): Avoid panics for UTF-8 characters in paths

---

minidump/src/cfi.rs

In case of error in `.debug_frame` section the CFI info in `.eh_frame` weren't retrieved.

feat(minidump): Get CFI info from eh_frame even if err in debug_frame

---

minidump/src/cfi.rs

Gimli has a hardcoded limit of 32 register rules per CFI row. There are rare occurrences where this limit is exceeded for single rows. In this case, it does not make sense to abort conversion, and instead just skip the row. 
Ref https://github.com/gimli-rs/gimli/pull/487

fix(minidump): Skip TooManyRegisterRules errors in CFI

---

debuginfo/src/base.rs
debuginfo/src/dwarf.rs

Calculates line record sizes for DWARF by comparing with the previous row emitted from the line number program. Additionally, the sequence end point is used to calculate the length for the last row/record.

fix(debuginfo): Calculate line record sizes for DWARF

---

debuginfo/src/dwarf.rs
debuginfo/src/pdb.rs
debuginfo/src/private.rs
debuginfo/tests/snapshots/test_objects__elf_functions.snap
symcache/tests/snapshots/test_writer__functions_macos.snap

Fixes an issue where in some cases the inline tree might have been composed wrong. This was particularly the case in DWARF information from Rust programs, as those often contain nested scopes within functions.
Previously, we only considered functions entries when flushing inlinees into the function stream. This was violated in a tree like this:
```
> parent
> inlinee 1
> scope
> inlinee 2
```
Invalid nesting:
```
> parent
> inlinee 1
> inlinee 2
```
Correct nesting:
```
> parent
> inlinee 1
> inlinee 2
```

fix(debuginfo): Detect all scopes when collecting inlinees

---

demangle/build.rs

fix(build): Broken compilation with -Clink-dead-code

---

Cargo.toml
examples/addr2line.rs

This adds a very naive implementation of `addr2line`, using the high-level functions provided by `Object` and `DebugSession`. It is able to use debug information as well as the symbol map to perform symbol lookups. The CLI is based on https://linux.die.net/man/1/addr2line.
This implementation has a few shortcomings, especially performance: 
- It iterates the full function list multiple times, and collects inline functions just to print out a few records. Optimizing this will require new lookup methods on the `DebugSession` trait.
- When running without `--inlines`, the outer function location is printed, instead of the inner one.
- There is a small chance for invalid lookups when multiple inlinees share code blocks (which can happen in release optimizations).
```
$ addr2line -Cifse …
```

feat(examples): Add a naive addr2line example

---

symcache/src/cache.rs

Ensures that for a lookup with inline frames the same instruction address is yielded for every frame instead of the caller function address. This allows Sentry to display proper inline markers.
When this was implemented originally, this changed address was supposed to show the instruction of the call in the parent. However, this can also be observed using `symbol_addr` on the inlinee. Having the same instruction address is technically more correct.
Notice the difference in instruction addresses. Inline frames are marked with a blue dashed underline.
**Before**
**After**

fix(symcache): Use same instruction address for full lookup

---

minidump/src/cfi.rs

We've seen files where the start/end addresses in `RuntimeFunction` entries are not matching up. Instead of causing an underflow error, we can skip such errors gracefully.
For reference, Breakpad's `dump_syms` fails with a failed assertion in this case.

fix(cfi): Skip invalid PE runtime function entries

---

minidump/src/cfi.rs

We've encountered files that contain CFI entries pointing before the load address of the image. Such entries are invalid, since they cannot be mapped to a relative address. Since such a file can still contain valid entries, rather skip them and continue.

fix(cfi): Skip invalid CFI entries instead of erroring out

---

debuginfo/src/pe.rs

Packers may strip original sections from PEs and replace them with stubs. In such a case, the exception table still contains references to sections like `.pdata`, even though they are in fact empty.
To detect this case, we scan for `.stub` sections. If such a section is present and `.pdata` is empty, then we report unwind info as missing. This check is extremely conservative so that it does not cause false positives.
```
Name    VAddr           VSize           PAddr           PSize           ...
.text	00001000	00442AB8	00000000	00000000	00000000	00000000	0000	0000	68000020	
.rdata	00445000	00098428	00000000	00000000	00000000	00000000	0000	0000	48000040	
.data	004DE000	00E68E34	00000000	00000000	00000000	00000000	0000	0000	C0000040	
.pdata	01347000	000075D8	00000000	00000000	00000000 …
```

fix(cfi): Detect stub DLLs and skip CFI generation

---

Makefile
py/.flake8
py/setup.py
py/symbolic/_compat.py
py/symbolic/common.py
py/symbolic/debuginfo.py
py/symbolic/proguard.py
py/symbolic/unreal.py
py/tests/test_crashprobe.py
py/tests/test_debug.py
py/tests/test_minidump.py
py/tests/test_sourcemaps.py

Python linting was misconfigured and tested a missing folder. Instead, we should lint the `py` subfolder. Since flake8 no longer seems to pick up the config file, we need to pin the version. Also, there are a few lints that needed fixing.

build(py): Pin flake8 and restore python linting

---

minidump/src/cfi.rs

Since unwind operator codes are variable-length encoded, it is not possible to reliably continue parsing once an unknown code has been encountered. Other functions in the same file can still continue valid unwind information, so rather than failing the entire file, just skip the invalid entries.
This is an expected error. Since more unwind operators could be added in the future, we should be lenient.

fix(cfi): Skip functions with unknown unwind codes

---

demangle/vendor/swift/README.md

Applies https://github.com/getsentry/symbolic/pull/208#discussion_r426354077, courtesy of @kastiglione.
> I think you can use `--skip-build` here. The headers in `build/Ninja-DebugAssert/*-macosx-x86_64/include` are still generated when `--skip-build` is used. This avoids building all of swift.
Thanks!

meta(demangle): Recommend to skip swift build

---

debuginfo/src/dwarf.rs

When an inline range is strictly included in a parent line record, it must be split into three parts and the end of the original line record must be retained for the last part. This fixes two distinct issues in the previous implementation:
1. The last record was always aligned with the end of the inlinee-range, which either made it too long or left a gap.
2. The third split was also patched with call site information, instead of retaining the original line info.
**Before patching**:
```
+-------------------+
Parent:  |         P         |
+---+-----------+---+
Inlinee:      |     I     |
+-----------+
```
**After patching**:
```
+---+-----------+---+
Parent:  | P |     C     | P |
+-------------------+
Inlinee:      |     I     |
+-----------+
```
(`P` parent line record, `C` Call site …

fix(debuginfo): Three-way split line records for inlinee-ranges

---

demangle/Cargo.toml
demangle/src/lib.rs

`cpp_demangle 0.2.17` was yanked from the registry.

fix(demangle): Upgrade to cpp_demangle 0.3.0

---

cabi/src/common.rs
cabi/src/symcache.rs
common/Cargo.toml
common/README.md
common/src/byteview.rs
common/src/cell.rs
common/src/fail.rs
common/src/heuristics.rs
common/src/lib.rs
common/src/path.rs
common/src/types.rs
examples/minidump_stackwalk.rs
minidump/src/cfi.rs

Updates doc comments all over `symbolic-common` with doc comments and improved descriptions, and also deprecates some APIs that are not future-proof:
- `pointer_size`, `instruction_alignment` and `ip_register_name` have moved from `Arch` to `CpuFamily`.
- `Arch::register_name` as been moved to `CpuFamily::cfi_register_name`.
- `CpuFamily::cfi_register_name` returns `None` instead of `Some("")` for some unknown registers.
- Field access on `InstructionInfo` has been deprecated and replaced with a builder.

doc(common): Add examples and improve common docs

---

common/Cargo.toml
common/src/byteview.rs
common/src/cell.rs
common/src/heuristics.rs
common/src/types.rs

Fixes a few cases that were missed in #246 and the `7.4.0` release. Also references the README from `Cargo.toml` so that it shows up on crates.io.

fix(common): Update doc comments and fix broken links

---

cabi/include/symbolic.h
cabi/src/debuginfo.rs
py/symbolic/debuginfo.py
py/tests/test_debug.py

It would be nice to have the method to create an archive from bytes buffer.
For instance, I have a zip archive with dSYM files and I have to unpack the zip archive to a temp directory, then call the method symbolic_archive_open for each file in order to get symbolic archive instance.
Instead of it, I want to just read the slice of bytes from the zip archive and create the symbolic archive instance from it without the necessity to save the buffer to a temporary file to open it further using current exposed methods
p.s. I've tried to generate heard file calling make file command but it failed due to rust compilation error, so I just added the new method to the file manually (I'm not good in rust to fix such errors)

C-ABI: Add method to create symbolic archive from bytes buffer

---

debuginfo/src/pdb.rs
debuginfo/tests/test_objects.rs
py/symbolic/debuginfo.py
py/symbolic/sourcemap.py
py/symbolic/symcache.py

ID records specify the mangled format for anonymous namespaces: `?A0x<id>`, where `id` is a hex
identifier of the namespace. Demanglers usually resolve this as "anonymous namespace".
This also fixes an issue with demangling: If the anonymous namespace is in the
beginning of the composed name, it leads the demangler to believe that this is a
mangled MSVC name. However, since this is a composed demangled name, this leads
to a demangle error.

fix(debuginfo): Detect mangled anonymous namespaces in PDB inlinees

---

Cargo.toml
unreal/Cargo.toml
unreal/src/context.rs
unreal/src/logs.rs
unreal/tests/test_unreal_crash_parse.rs

Streamlines the feature name for serde in `symbolic-unreal` with other crates.

build(unreal): Rename with-serde to serde

---

CHANGELOG.md
py/symbolic/minidump.py
symbolic-common/src/heuristics.rs
symbolic-common/src/types.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-unreal/src/context.rs
symbolic-unreal/tests/snapshots/test_unreal_crash_parse__contexts_runtime_properties.snap

Removes all deprecated items from the public API both in Rust and in python.

ref: Remove all deprecated items

---

symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-minidump/src/cfi.rs
symbolic-symcache/src/writer.rs

This avoids both boxing, and unsafely transmuting the symbol iterators.

fix: Add a SymbolIterator and Lifetimes to ObjectLike trait

---

symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/src/sourcebundle.rs

ref: Add File/FunctionIterator and lifetimes to DebugSession

---

symbolic-debuginfo/Cargo.toml
symbolic-symcache/Cargo.toml

dmsort 1.0 misuses `mem::uninitialized` which is now leading to a panic
which causes problems for certain symbols.
Refs https://github.com/emilk/drop-merge-sort/issues/2

fix(debuginfo): Update dmsort to 1.0.1 to avoid panic due to UB

---

examples/addr2line/src/main.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/pdb.rs
symbolic-symcache/src/cache.rs
symbolic-symcache/src/writer.rs
symbolic-unreal/Cargo.toml
symbolic-unreal/tests/snapshots/test_unreal_crash_parse__contexts_runtime_properties.snap

ref: Updates for rust 1.48

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

This ensures we're aware of issues with newer rust compilers sooner.
We run clippy and tests in the same step since caching matters more
than speed of completion as this does not block PRs.
No explicit caching since the compiler changes every time anyway.

ci: Run rust nighlty on a schedule

---

symbolic-debuginfo/src/dwarf.rs

It would appear that rustc is emitting bad sequences for WASM we need
to skip.  See comment for rationale of why we can work around this.
Refs https://github.com/rust-lang/rust/issues/79410

fix(dwarf): Skip line program sequences at 0

---

symbolic-debuginfo/src/dwarf.rs

We generally trust the symbol table to contain more accurate names than DW_AT_name and other attributes on DIEs in DWARF debug information. Some C++ compilers have been known to output truncated or simplified names into these attributes, whereas the symbol table always contains accurately mangled names.
The Dart compiler is an exception to this case. Its name mangling appears to be lossy and there is no generally available demangler. Thus, we need to prefer the demangled DW_AT_name.
Example:
- Mangled Symbol: `Precompiled__pM_658260265_sEa__anonymous_closure__8632`
- Demangled Symbol: `_MyAppState.build.<anonymous closure>`
Obtained via `cargo run -p addr2line -- -fCi -e app.symbols 0x211b7c` from [this example](https://github.com/getsentry/sentry-dart/blob/6be1283348b5f303de38099669a9fe9e …

fix(debuginfo): Prefer DWARF names for Dart functions

---

symbolic-common/src/types.rs
symbolic-debuginfo/src/wasm.rs

Since there are two wasm architectures (32 and 64) we should be explicit about the architectures in code.
See https://github.com/WebAssembly/design/blob/master/CAndC%2B%2B.md

feat: Rename architecture to wasm32

---

symbolic-cabi/src/core.rs
symbolic-symcache/src/cache.rs
symbolic-symcache/src/error.rs
symbolic-symcache/src/format.rs
symbolic-symcache/src/writer.rs

Follows the conventions set by `std::io::Error`.

ref(symcache): Switch to error with kind

---

symbolic-cabi/src/core.rs
symbolic-unreal/src/container.rs
symbolic-unreal/src/error.rs
symbolic-unreal/src/logs.rs

Follows the conventions set by `std::io::Error`.

ref(unreal): Switch to error with kind

---

symbolic-cabi/src/core.rs
symbolic-minidump/src/cfi.rs

Follows the conventions set by `std::io::Error`.

ref(minidump): Switch to error with kind

---

symbolic-cabi/src/core.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-debuginfo/src/wasm.rs

Follows the conventions set by `std::io::Error`.

ref(debuginfo): Switch to error with kind

---

Makefile

With pytest 6, the internal representation of tests seems to have changed. Our overrides in `conftest.py` no longer emit compatible output which causes pytest to fail with an `INTERNALERROR`.
Until we get that fixed, this pins pytest to v5.

fix(pytest): Pin pytest 5 for debugfail customizations

---

symbolic-unreal/Cargo.toml
symbolic-unreal/src/logs.rs

Updates anylog and symbolic's own log parsing code to avoid panics when invalid or ambiguous dates are specified in the unreal crash log stream.
Ref mitsuhiko/rust-anylog#4
Ref mitsuhiko/rust-anylog#5

fix(unreal): Avoid panic during log parsing

---

.github/workflows/build.yml
.github/workflows/release.yml
scripts/bump-version

Switches the release process to the centralized release action. Craft is run directly on the host and requires `cargo` in it's bump-version script.
To match conventions from other repositories, the former release build workflow has been renamed to "Release build" and moved to `build.yml`.

ci(gha): Switch to release workflow

---

.github/workflows/build.yml
CHANGELOG.md

Starting with 8.0.0, the sdist package was missing the Breakpad and LSS third-party submodules and therefore would not build. After merging this, we will release 8.0.2 with a fixed sdist.
Note that this increases the size of the sdist. This could be reduced by removing Breakpad's binaries and test fixtures before bundling the package. Since the wheel is still reasonable in size, however, we can defer that until there is actual demand for it.
Fixes #309

fix(build): Ensure submodules are included in sdist

---

symbolic-debuginfo/Cargo.toml

Downgrades wasmparser to 0.59.0 to match the version `walrus` uses. This avoids
a duplicate dependency in the dependency tree.

build(debuginfo): Match wasmparser version from walrus

---

symbolic-debuginfo/src/elf.rs

MIPS compilers put debugging information in sections of type `SHT_MIPS_DWARF`
instead of `SHT_PROGBITS`. Apart from the different section type, contents are
largely equivalent and symbolic is able to process them.

fix(elf): Consider sections of type SHT_MIPS_DWARF

---

symbolic-symcache/src/format.rs
symbolic-symcache/src/writer.rs

SymCaches store line records where record specifies the delta to the previous line record. These deltas are stored as `u8` to save space for the common case where only small increments are needed. If two records are more than `0xff` apart, we insert filler line records.
This PR solves two bugs in creating these filler line records:
1. The delta was computed with `(diff & 0xff) as u8` instead of `diff.min(0xff) as u8`. This means that there was an address drift every time we had to insert filler line records.
2. The filler line records are technically still part of the previous range. However, they already carried information of the next line record, leading to wrong line numbers.
**SymCache version is incremented to `6`.** 
The previous implementation originates …

fix(symcache): Compute correct line offsets

---

symbolic-symcache/src/format.rs

Fixes part of https://github.com/getsentry/symbolic/issues/284#issuecomment-715587454
Public symbol records often have no size. If there's a gap larger than 65k, the symcache lookup would not resolve the last symbol. For example, with this Breakpad symbol a lookup for `0x180000` should resolve `symbol_a`:
```
PUBLIC 100000 0 symbol_a
PUBLIC 200000 0 symbol_b
```
In practice, it is likely that there are symbols missing and the lookup would in fact be wrong. However, there could be the possibility of such large functions and with how symbol tables are structured, this would be the expected result. Note that this now also matches Breakpad's behavior.

fix(symcache): Support lookup for public syms larger than 65k

---

symbolic-symcache/Cargo.toml
symbolic-symcache/src/format.rs
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/test_writer.rs
symbolic-testutils/fixtures/libgallium_dri.sym
symbolic-testutils/fixtures/xul.sym

@jan-auer and I believe that there is no reason to consider functions of length 0 in `symcache` and all such functions occurring in a debug object should be discarded before building the cache. The type of the `len` field of the `FuncRecord` struct is changed from `u16` to `NonZeroU16` to enforce this invariant.

ref(symcache): FuncRecord::len must be nonzero

---

symbolic-debuginfo/src/dwarf.rs

The values of the `DW_AT_low_pc` and `DW_AT_high_pc` attributes can also contain
`DW_FORM_addrx*`. We did not support this and used to raise an unreachable
panic.
To handle this more gracefully, symbolic will now return an error. This error
matches what gimli's `Dwarf::attr_addr` returns in the same case.
Note that this will complicate debugging. The `DwarfError` struct does not carry
a backtrace yet, so we will no longer know which attribute causes the error.
Once backtraces are stable in the standard library, we can reintroduce this with
a feature flag.

fix(debuginfo): Support debug_addr indexes in DWARF functions

---

Makefile

I also slightly changed the beginning of the `Makefile` to unify it with the one in `symbolicator`.
When I run `make test` locally, quite a lot of tests fail, is that expected?

build: Replace virtualenv with venv

---

symbolic-debuginfo/src/breakpad.pest

The added descriptions are the first sentences in the description of the records at https://github.com/google/breakpad/blob/master/docs/symbol_files.md#module-records.

doc(debuginfo): Add descriptions of records to breakpad.pest

---

symbolic-common/Cargo.toml
symbolic-common/src/byteview.rs
symbolic-common/src/cell.rs
symbolic-common/src/path.rs
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/private.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-debuginfo/tests/test_objects.rs
symbolic-demangle/Cargo.toml
symbolic-demangle/tests/test_detection.rs
symbolic-demangle/tests/test_objcpp.rs
symbolic-minidump/Cargo.toml
symbolic-minidump/tests/test_cfi.rs
symbolic-sourcemap/Cargo.toml
symbolic-sourcemap/src/lib.rs
symbolic-symcache/Cargo.toml
symbolic-symcache/tests/test_compat.rs
symbolic-unreal/Cargo.toml
symbolic-unreal/src/context.rs
symbolic-unreal/src/logs.rs
symbolic-unreal/tests/test_unreal_crash_parse.rs

For dog fooding diffed assertions.

test: Add similar-asserts' assert_eq

---

symbolic-demangle/src/lib.rs

This is a port of https://github.com/mstange/msvc-demangler-rust/pull/60 to `symbolic-demangle`.

feat(demangle): Demangle Md5 names by doing nothing

---

symbolic-demangle/Cargo.toml
symbolic-demangle/src/lib.rs
symbolic-demangle/tests/test_cpp.rs

This is a port of https://github.com/gimli-rs/cpp_demangle/pull/210 to `symbolic-demangle`.

feat(demangle): Strip hash suffixes from C++ function names

---

symbolic-unwind/src/base.rs
symbolic-unwind/src/evaluator/mod.rs
symbolic-unwind/src/evaluator/parsing.rs

This makes two changes to the way we parse Breakpad expressions:
- Numbers are signed and decimal
- Constants and variables have their valid names restricted to `\.[a-zA-Z0-9]+` and `\$[a-zA-Z0-9]+`, respectively.

fix(parser): Correct handling of numbers and identifiers

---

symbolic-unwind/src/base.rs

Since numbers in Breakpad stack records can be negative, we'll need implementations for i32 and i64.

feat(unwind): i32 and i64 implement RegisterValue

---

symbolic-unwind/src/base.rs
symbolic-unwind/src/evaluator/parsing.rs

The `expr` parser now automatically interprets e.g. `$foo -17 +` as `$foo 17 -`. In all other contexts, negative numbers are an error. This is because conceptually these expressions are always supposed to be positive, but sometimes negative offsets occur in CFI rules and program strings.
Semi-independently of that, the `expr` parser is now smarter as well. It parses `$foo 17 -` as one expression with no input left over, but `$foo 17` as `$foo` with ` 17` left over. This accounts for some of the added complexity of the parser (we need to remember when we had last parsed a complete expression), but the majority is caused by having to record the signs of subexpressions and making lots of case distinctions about when negative numbers are valid.
I am not particularly happy with this. @jan-auer …

fix(unwind): Only allow negative numbers on rhs of addition

---

symbolic-debuginfo/src/breakpad.pest
symbolic-debuginfo/src/breakpad.rs
symbolic-minidump/src/cfi.rs

This turns `BreakpadStackCfiRecord` into an enum with two variants (`Init` and `Delta`) and factors address/size information out of the `text` field.

ref(debuginfo): Improve representation of Breakpad cfi records

---

symbolic-debuginfo/src/breakpad.pest
symbolic-debuginfo/src/breakpad.rs
symbolic-minidump/src/cfi.rs

As per @jan-auer's suggestions, a `BreakpadStackCfiRecord` now bundles together an init record and its associated "delta "records.

ref(debuginfo): Further refactor Stack CFI records

---

.github/workflows/periodic.yml
symbolic-common/src/types.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/object.rs
symbolic-minidump/src/processor.rs
symbolic/README.md
symbolic/src/lib.rs

Fix some clippy warnings and disable some that we can't or want
to fix, because they're from a third party or would break the API.
The Into -> From changes are possible since the orphan rules have
been relaxed in Rust 1.41.  So we no longer work on older rust
versions.
Also bring the periodic CI job to the same level as the symbolicator
one.  Allowing to run it on demand and continue tests when one
fails.

ref(compiler): Upgrade to Rust 1.51

---

symbolic-debuginfo/src/breakpad.pest
symbolic-debuginfo/src/breakpad.rs
symbolic-minidump/src/cfi.rs

This PR mainly serves to structure `BreakpadStackWinRecord` in a similar way as `BreakpadStackCfiRecord`. One thing I am not entirely sure about is how to handle the issue of program string vs `allocates_base_pointer` field. Briefly, the next-to-last field of a `STACK WIN` record indicates whether the last field is a program string or an `allocates_base_pointer` flag. For now I just gave the struct fields for both and set the one that isn't used to a dummy value, but that's not exactly the most rigorously typed solution. Is this good enough or should I use e.g. an enum?
Aside from `BreakpadStackWinRecord`, there is also new constructor for the `BreakpadStackRecords` iterator and the `BreakpadStackCfiRecord::parse` method has had its `deltas` argument removed.

ref(debuginfo): Breakpad stack record refactoring

---

symbolic-debuginfo/src/macho/bcsymbolmap.rs
symbolic-debuginfo/src/macho/mod.rs

The erorr kind was erroneously not exposed on the public API.

fix(bcsymbolmap): Expose error kind

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/macho/bcsymbolmap.rs
symbolic-debuginfo/src/macho/mod.rs

But the type this time round is a simple mapping of UUIDs, the plist
is never representable itself so stays out of the API and allows us to
change the implementation.

feat(debuginfo): Add back PList parsing

---

symbolic-unwind/src/evaluator/mod.rs
symbolic-unwind/src/evaluator/parsing.rs

From real-world data it's clear that constants actually don't have to have a leading `.`.

fix(unwind): Constants don't have to start with .

---

Cargo.toml
symbolic-minidump/Cargo.toml
symbolic-minidump/benches/from_minidump.rs
symbolic-minidump/benches/from_minidump_external.rs
symbolic-minidump/tests/test_processor.rs

This adds a simple `criterion` benchmark that corresponds to the existing `process_minidump_linux_cfi` test. It precomputes a `FrameInfoMap` and then runs `ProcessState::from_minidump`.

feat(minidump): Benchmark stackwalking w criterion

---

symbolic-symcache/src/cache.rs

The lifetime of the `&self` reference in several `LineInfo` methods does not need to be tied to the lifetime of the structure.

ref(symcache): Liberalize lifetimes in methods

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/benches/breakpad_parser.rs

This adds a group of `criterion` benchmarks that test the various Breakpad record parsers.

test(debuginfo): Benchmark breakpad parsers

---

py/symbolic/debuginfo.py
symbolic-cabi/include/symbolic.h
symbolic-cabi/src/debuginfo.rs
symbolic-debuginfo/src/macho/bcsymbolmap.rs

This provides a minimal Python API for the BcSymbolMap and UuidMapping
types which is sufficient to support the formats in sentry.
Related PRs:
https://github.com/getsentry/sentry/pull/25712
https://github.com/getsentry/sentry-cli/pull/952
https://github.com/getsentry/symbolicator/pull/414

feat(py): Support BCSymbolMap on python API

---

symbolic-symcache/src/cache.rs
symbolic-symcache/src/writer.rs

Instead of failing hard when hitting the max file limit, we rather emit
a sentinel for every file that exceeds the limit.
I tested this on https://symbols.electronjs.org/Electron%20Framework/8DE7618E965231A7B4CDD1C701077B9B0/Electron%20Framework.sym which previously ran into this limit and failed symcache conversion.

fix: Handle too many files more gracefully

---

examples/symcache_debug/src/main.rs
symbolic-cabi/src/core.rs
symbolic-cabi/src/lib.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/macho/mod.rs
symbolic-debuginfo/src/wasm.rs
symbolic-demangle/tests/test_swift.rs
symbolic-minidump/src/cfi.rs

I just allowed the str_radix lint since it leaded to uglier code.
Similarly, I think the manual_flatten is too strict, I will file an issue upstream.

fix: Make clippy 1.52 happy

---

.github/workflows/periodic.yml

This seemed to break the entire periodic job and no one seems to get
any notifications for that.  Ugh.

ci(periodic): Fix fail-fast config

---

symbolic-common/src/path.rs

Nightly clippy does not like it if these statements are repeated in
all branches.

build(clippy): Move common statement out of branches

---

symbolic-debuginfo/src/sourcebundle.rs

This field was written but never used, and it is private.  So it was
dead code.  Thanks nightly clippy.

ref(clippy): Remove unused private field

---

symbolic-debuginfo/src/breakpad.pest
symbolic-debuginfo/src/breakpad.rs
symbolic-minidump/src/cfi.rs

Breakpad officially only handles record types `0` and `4`, but we do sometimes get records of other types.

fix(breakpad): Handle all WIN record types

---

symbolic-unwind/src/base.rs
symbolic-unwind/src/evaluator/mod.rs

This adds an `Into<u64>` bound and makes the associated constant `WIDTH` a `u8` instead of a `usize`.

ref(unwind): Minor changes to RegisterValue trait

---

symbolic-unwind/src/evaluator/mod.rs

This interface is intentionally simple and not optimized for e.g. finding the value of a single register.

feat(unwind): Add interface for CFI rules to evaluator

---

py/tests/res/minidump/crash_macos.sym
py/tests/test_minidump.py
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/macho/compact.rs
symbolic-debuginfo/src/macho/mod.rs
symbolic-minidump/src/cfi.rs
symbolic-minidump/tests/snapshots/test_cfi__cfi_macho.snap

This is a WIP implementation of #368. It appears to generate reasonable-looking `STACK CFI` records, though I haven't tested them yet.
A few major questions that need feedback from the symbolic folks:
* Where should this implementation go (gimli, goblin, another symbolic- crate..?)
* What should this implementation use as the basis for its parsing/error-handling (currently using gimli for everything, bad choice for the errors)
* How should this handle *conflicting* `STACK CFI` records between the DWARF CFI sections and the compact unwinding sections? This is not theoretical -- this happens on e.g. libmozglue in release firefox distributions.
The conflicting records has been kind of useful for being able to see that my output does indeed seem reasonable, as it largely agrees with the DWARF …

Implement compact unwinding info

---

symbolic-unwind/Cargo.toml
symbolic-unwind/src/base.rs
symbolic-unwind/src/evaluator/mod.rs

As @Gankra suggested at https://github.com/luser/rust-minidump/pull/161, this replaces the arithmetical operations in the CFI evaluator with safe versions. `num-traits` is used to do this in a generic way. This also necessitates some changes to error types that were previously monomorphic.

fix(unwind): Make evaluation safe

---

symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho/mod.rs

Nightly clippy doesn't like these and prefers a for loop.  For
BreakpadSymbolIterator clippy also didn't like the nested if-let in
the resulting for loop so that's re-written even further.

ref(clippy): Avoid more while-if-let

---

py/tests/res/minidump/crash_macos.sym
symbolic-minidump/src/cfi.rs
symbolic-minidump/tests/snapshots/test_cfi__cfi_macho.snap

This is on top of #388 
This specific function has some hand crafted dwarf expressions
that we currently can't process. They encode how to restore the
registers from a machine context accessible via `$rbx`
See: https://github.com/apple/darwin-libplatform/blob/215b09856ab5765b7462a91be7076183076600df/src/setjmp/x86_64/_sigtramp.s#L198-L258

fix: Hardcode unwind info for _sigtramp

---

symbolic-demangle/Cargo.toml

This update finally includes our patches and avoids the need to pull it from a git dependency.

fix: Update msvc-demangler

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/dwarf.rs

Updates gimli to 0.24 and removes the public re-export. To do that we copy-pasted our own Endian enum.
*technically breaking*

ref: Update gimli

---

examples/dump_sources/src/main.rs
examples/minidump_stackwalk/src/main.rs
symbolic-cabi/src/proguard.rs
symbolic-common/src/path.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho/compact.rs
symbolic-debuginfo/src/pdb.rs
symbolic-minidump/src/cfi.rs
symbolic-minidump/src/processor.rs
symbolic-minidump/tests/test_processor.rs
symbolic-symcache/src/cache.rs
symbolic-unreal/src/container.rs
symbolic-unreal/src/context.rs
symbolic-unreal/src/logs.rs
symbolic-unwind/src/evaluator/mod.rs

These are double references which the compiler silently derefed
immediately.

ref(clippy): Avoid needles references

---

symbolic-debuginfo/src/breakpad.rs

I somehow missed some clippy lints when merging the breakpad parser PR.

fix(debuginfo): Remove unnecessary references

---

symbolic-debuginfo/src/macho/compact.rs
symbolic-minidump/src/cfi.rs
symbolic-symcache/src/format.rs
symbolic-symcache/src/writer.rs

`libsystem_kernel.dylib` has the following entries which would previously result in an error:
```
[211]: function offset=0x000121c3, encoding[7]=0x00000000
[212]: function offset=0x000121c3, encoding[28]=0x04000680
```
This also has a driveby off-by-one fix for the `parent_offset`, since `0xFFFF` is the sentinel value for "no parent".

fix: Allow for duplicate compact unwind entries

---

symbolic-minidump/Cargo.toml
symbolic-minidump/benches/nested_range_map.rs
symbolic-minidump/src/processor.rs

This adds a `RangeMap` struct containing a set of disjoint ranges. It has significant overlap with `symbolic_debuginfo::SymbolMap`, but is generic.

feat(unwind): Add RangeMap struct

---

.craft.yml

The manylinux2010 build image now generates wheels compatible with
additional python environments. We add a wildcard to ignore these
additional environments.

meta: Update Craft config

---

symbolic-debuginfo/src/macho/compact.rs

My blogpost is generated with rustdoc so I had lots of opportunities to nitpick the rendered result :)

backport compact_unwind doc cleanups from article

---

symbolic-minidump/src/cfi.rs

symbol_map is a Vec that is quite expensive to create, so doing it every time we encounter a dwarf FDE entry is extremely quadratic and slow. This causes macos firefox builds to timeout while trying to dump the symbols for XUL -- especially for aarch64 builds (for whatever reason). 
You can test that out by running dump_syms on the XUL inside target.dmg for this build: https://treeherder.mozilla.org/jobs?repo=try&revision=5a2fbeb4112cd87eee7bb3f1b48223fc9b3ff7b9&selectedTaskRun=O2kbKrM-RauVaLGx-7f0MA.0
This change drops dump_syms on XUL from ~2.5 minutes to ~4 seconds on my macbook pro.

fix(cfi): Don't build the MachO symbols in the loop

---

symbolic-minidump/src/cfi.rs

Uses a simple ASCII preamble.
One thing to note is that this header is being stripped when doing `as_slice` as to not pass it
through to breakpad.

fix: Introduce CfiCache versioning

---

symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/tests/snapshots/test_objects__elf_functions.snap
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/snapshots/test_writer__functions_linux.snap
symbolic-symcache/tests/test_writer.rs

The `DwarfDebugSession::functions` Iterator can yield duplicated functions, which, combined with a ton of inlinees can blow out the `ParentOffset` limit.
This does fix the symptom of these duplicated functions, but I would say that the real fix would rather be somewhere in the Iterator that yields these values.

fix: Skip over duplicated functions in SymCaches

---

CHANGELOG.md
symbolic-minidump/src/cfi.rs

On top of #399 , this PR actually implements writing the preamble with its version information.

fix: Write the new CFI cache version to its file

---

symbolic-debuginfo/src/pdb.rs

Some PDBs fail processing because some inlinees result in invalid checksum errors. I suspect this might be because of broken file index annotations. Instead of failing the complete file, we silently skip these now.
Should solve https://getsentry.atlassian.net/browse/ISSUE-1238, and have that file process successfully.

fix: Skip broken inlinees in PDBs

---

symbolic-minidump/src/processor.rs

The primary reason to do this was insertion performance, which is pretty bad for the vector-based implementation. That implementation's advantage (and my reason for choosing it initially) was binary search, but `BTreeMap` allows something similar in the form of the `range` method, so there's really no reason left not to use a `BTreeMap`. In my local tests this change has a positive impact on stackwalking performance.
`NestedRangeMap` is, unfortunately, still fairly Byzantine, with many edge cases to consider. I believe it's reasonably well tested, including property-based tests.

ref: Rewrite of (Nested)RangeMap based on BTreeMap

---

symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/macho/mod.rs

This was missed in #414, the symbolmap was passed recursively to the function, but never actually used.

fix: Apply BcSymbolMap names to inlinee names

---

symbolic-minidump/Cargo.toml

In particular, this omits `third_party/lss/.git`, which is currently included in the Cargo package. That file is problematic because it causes issues with vendoring `symbolic-minidump` into a Git repository (Git refuses to track it, causing Cargo to complain about a .cargo-checksum.json violation).

fix: Include only the relevant header file from third_party/lss

---

symbolic-debuginfo/src/elf.rs

Expose dynamic symbols in ELF files

---

symbolic-unreal/src/container.rs

Nightly compiler complains that uncompressed_size and file_count are
never read and thus dead code.  However this is part of the header
struct and we need them defined to read the structures correctly even
if we do not use the fields.  So allow it as dead code.

fix(dead_code): Allow dead code to silence warnings

---

CHANGELOG.md
symbolic-demangle/src/lib.rs

This was splitting strings in an unsafe way, assuming you could always
split at 33 bytes from the end which is not true in UTF-8 strings.
Fixes SYMBOLICATOR-GE

fix: Safe multibyte char string splitting

---

examples/object_debug/src/main.rs
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho/mod.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-debuginfo/src/wasm.rs
symbolic-debuginfo/tests/test_objects.rs

This is a proof of concept PR to demonstrate an excessive solution that could be used to sidestep problems like the one mentioned in https://github.com/getsentry/sentry-dart/issues/591, where only a portion of an ELF is malformed but the rest of it can be perfectly parsed. The ELF parser has been changed so that malformed ELFs could still be partially parsed out instead of eagerly failing at the first error.
The PR basically copy-pastes nearly everything from goblin's ELF parser, and replaces all short-circuited errors with a macro that returns the ELF object with everything successfully parsed up until the failure. A good second iteration on this would be to merely skip unparseable pieces but not short-circuit on the first failure, allowing us to, for example parse out dynamic symbols …

Be incredibly lenient when parsing ELFs

---

symbolic-debuginfo/src/elf.rs
symbolic-demangle/tests/utils/mod.rs
symbolic-minidump/build.rs

Apparently we should prefer direct assert!.  Also an unnecessary
closure was used.

ref(clippy): Some nightly clippy fixes

---

symbolic-unreal/src/container.rs
symbolic-unreal/src/error.rs

To avoid unbounded allocation on bad input data, this PR introduces a new API
`Unreal4Crash::parse_with_limit` that allows specifying a maximum allocation
size.

fix(unreal): Allow to parse with limit [INGEST-565]

---

symbolic-unreal/src/container.rs

UE5 introduced a `"CR1"` marker at the beginning of crash archives. It indicates
that the header at the beginning of the file is valid. Previously, that header
was merely a placeholder and a second header at the end of the file contained
valid information. `Unreal4Crash::parse` now supports both versions by checking
for "CR1".
See https://github.com/EpicGames/UnrealEngine/commit/a0471b76577a64e5c4dad89a38dfe7d9611a65ef
Fixes https://github.com/getsentry/sentry/issues/29940
cc @redxdev

fix(unreal): Support the UE5 crash reporter

---

CHANGELOG.md
symbolic-common/src/byteview.rs

This adds constructor to mmap a File into a ByteView without consuming
the file object.

feat(byteview): Add non-consuming mmap constructor

---

symbolic-symcache/src/new/compat.rs
symbolic-symcache/src/new/lookup.rs
symbolic-symcache/src/new/raw.rs

This changes `lookup::Function` and `lookup::File` so that the various string fields are resolved more eagerly. Consequently, these types don't need to keep a reference to the symcache and can make do with only one lifetime parameter.
Moreover, `Function` gains an additional `&str` for the compilation directory.

ref(symcache): Simplify Function & File lookup types

---

symbolic-symcache/src/new/lookup.rs
symbolic-symcache/src/new/mod.rs
symbolic-symcache/src/new/raw.rs
symbolic-symcache/src/new/writer.rs

This changes the new symcache format so that strings are prefixed with their own length (as a `u32`) before concatenating them. Consequently, they can then be indexed by a byte offset into the big string concatenation.

ref(symcache): Change internal string representation

---

symbolic-symcache/src/new/lookup.rs
symbolic-symcache/src/new/raw.rs
symbolic-symcache/src/new/writer.rs
symbolic-symcache/tests/breakpad.rs
symbolic-symcache/tests/test_writer.rs

Running the sentry-integration tests, I noticed the case that functions have an explicit *end*, which symbols do not have.
To handle this case, we optionally persist an end marker into the SymCache ranges, which we then match on to avoid returning a symbolicated symbol for lookups exceeding that end marker.

fix: Put an explicit end range into the SymCache

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/wasm.rs
symbolic-debuginfo/src/wasm/parser.rs

Opening as a draft since this PR depends on #470 
As stated in #472, this PR removes walrus due to its passively maintained status, and instead uses `wasmparser` directly. This means that not only can `wasmparser` be upgraded to follow the latest version much more easily and remove a dependency, it also means the runtime memory usage and CPU time should be greatly reduced as walrus was doing a _lot_ more work when parsing than this implementation, which (other than the bits needed for validation) only parses the sections/content actually used by this crate.
Resolves: #472

Replace walrus

---

symbolic-unwind/src/evaluator/mod.rs

Nightly clippy wants to decorate this with must_use because they
return Self.  I'm not really sure how safe it is to add something like
this.
https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use

ref(clippy): Decorate with must_use

---

symbolic-debuginfo/Cargo.toml

`elementtree` is only used for BCSymbolMaps, so this just makes it an optional dependency gated by `macho`. I noticed this because `elementtree` -> `string_cache` -> `phf_shared` is using an outdated version (0.8.0 vs 0.10.0).

Make elementtree optional

---

symbolic-common/src/byteview.rs

On Windows, Files can only be unlinked if there are no active handles to it.

fix: Fix test assertion on windows

---

.codecov.yml
.github/workflows/ci.yml
README.md

I was able to work around an unexplainable failure in my own action which seems to work now in sentry-rust, and I am experimenting there with `cargo-llvm-cov` as well: https://github.com/getsentry/sentry-rust/pull/398 (plus contributing some rustdoc-related fixes there and in the compiler)
For the time being, lets see how `fucov` does on this workspace.
Should fix #227

ci: Add Code Coverage Job

---

symbolic-debuginfo/src/sourcebundle.rs

I noticed this when reimplementing some of sentry-cli's upload-difs portions, basically the exact same input objects (in our case wasm binaries + source bundles) would always say there were missing chunks on the server, The cause of which was the use of a HashMap to store the files in the source bundle manifest, which will give non-deterministic output with the same input due to the default HashMap hash randomization. Changing to use a BTreeMap gives deterministic ordering so that the same input object will always give the same output source bundle. 
Also just want to note, the only reason that this is the case is that PR #470 changed the zip crate to remove default features, one of which is `time`, which when not present will always use [`1980-01-01` for the …

Use BTreeMap instead of HashMap for source bundle manifest

---

symbolic-debuginfo/src/elf.rs
symbolic-demangle/src/lib.rs

The `clippy::non-send-fields-in-send-ty` rule that fails on beta is either being turned off in nightly, or had some false positives that were fixes, as nightly clippy does not trigger those beta errors anymore.
I opted to just ignore the `#[must_use]` suggestion, as that would essentially be a public API change/break that I would like to avoid.

ref: Pacify nightly clippy

---

symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/wasm/parser.rs
symbolic-debuginfo/tests/snapshots/test_objects__wasm_symbols.snap
symbolic-symcache/src/new/writer.rs

Well, this took me longer than I would have liked to figure out, but I _think_ this resolves an issue with (malformed?) DWARF debug info and `SymCacheConverter`.
For some background, I noticed that when sending wasm stacktraces to sentry.io, the first frame in a very short stacktrace of < 5 frames was always misattributed, but other frames were correct. At first I assumed that I had messed up the WASM parsing in #474 somehow, but when looking at the addresses/symbols reported by [`wasmtime::Trap`](https://docs.rs/wasmtime/latest/wasmtime/struct.Trap.html) and the information parsed by `WasmObject` they were almost the same, other than that both wasmtime and DWARF use the "true" function start address, whereas in the previous code and the refactor it was using the address after the …

Fix WASM symbolication

---

symbolic-debuginfo/src/wasm.rs
symbolic-debuginfo/src/wasm/parser.rs

When encountering an invalid wasm header, the parser yielded an error, but never advanced its parser.
The `flatten()` call meant that we tried re-parsing in a loop.
Early-returning from the parser might be a bit too harsh, given that we would want to be as lenient as possible, but lets revisit that later on when we actually have to deal with broken-but-still-somehow-valid wasm files.
CC @Jake-Shadle since you recently wrote that piece of code

fix: Avoid infinite loops parsing invalid wasm

---

CHANGELOG.md

We should tag this as `8.6.0` due to quite a few new features.

meta: Draft new CHANGELOG

---

CHANGELOG.md
examples/addr2line/Cargo.toml
examples/addr2line/src/main.rs
examples/dump_cfi/Cargo.toml
examples/dump_cfi/src/main.rs
examples/dump_sources/Cargo.toml
examples/dump_sources/src/main.rs
examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs
examples/object_debug/Cargo.toml
examples/object_debug/src/main.rs
examples/symcache_debug/Cargo.toml
examples/symcache_debug/src/main.rs
examples/unreal_engine_crash/Cargo.toml
examples/unreal_engine_crash/src/main.rs
symbolic-debuginfo/Cargo.toml

This updates `goblin` which includes a couple of fuzzer fixes.
As well as `clap` which required some changes to example executables.

ref: Update dependencies

---

symbolic-minidump/src/processor.rs

We unconditionally inverted a Breakpad heuristic for ARM stack frames, not taking into account that the heuristic was never applied to the first frame in the stack. This led to some incorrect instruction addresses in ARM context frames.

fix(minidump): Don't unapply heuristic for context frame

---

examples/addr2line/Cargo.toml
examples/addr2line/src/main.rs
examples/dump_cfi/Cargo.toml
examples/dump_cfi/src/main.rs
examples/dump_sources/Cargo.toml
examples/dump_sources/src/main.rs
examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs
examples/object_debug/Cargo.toml
examples/object_debug/src/main.rs
examples/symcache_debug/Cargo.toml
examples/symcache_debug/src/main.rs
examples/unreal_engine_crash/Cargo.toml
examples/unreal_engine_crash/src/main.rs

The clap `App` type is deprecated since version _3.1.0_ and has been replaced with `Command`.
https://docs.rs/clap/3.1.1/clap/struct.App.html

fix(lint): Replace use of deprecated clap API

---

CHANGELOG.md
symbolic-debuginfo/src/elf.rs

The `gold` linker creates `.eh_frame` and related sections with type `SHT_X86_64_UNWIND` rather than `SHT_PROGBITS`. Right now, symbolic skips those sections and as a result does not detect unwind information. 
Breakpad and elfutils instead permit all section types _other than_ `SHT_NOBITS`.
See https://github.com/magma/magma/issues/10893

fix(debuginfo): Detect SHT_X86_64_UNWIND from gold

---

CHANGELOG.md

Adds the changelog entry for #503 and ensures that every changelog entry has the
PR linked.

meta: Amend changelog for 8.6.1

---

symbolic-symcache/src/lib.rs
symbolic-symcache/src/new/compat.rs
symbolic-symcache/src/new/mod.rs
symbolic-symcache/src/new/transform.rs
symbolic-symcache/src/new/writer.rs
symbolic-symcache/tests/test_writer.rs

These allow transforming the function and source location records that
will be written into SymCaches.
fixes https://github.com/getsentry/symbolic/issues/422

feat: Add SymCache Transformers (NATIVE-463)

---

symbolic-minidump/src/cfi.rs

The structure of STACK WIN records is described in https://github.com/google/breakpad/blob/master/docs/symbol_files.md#stack-win-records. In particular:
* The `has_program_string` flag should be 
* For `FrameData` (type 4) records: `1` if the record has a program string, `0` otherwise;
* For `FPO` (type 0) records: always `0`.
* The last argument should be
* For `FrameData` records: the program string if it exists, empty otherwise;
* For `FPO` records: `1` if the frame pointer register is used as a general-purpose register, `0` otherwise.
However, this is not what the current code does; we instead unify `has_program_string` and `uses_base_pointer` into one flag. Kudos to rust-minidump for discarding the resulting invalid records and logging this fact.

fix: Write STACK WIN records correctly

---

symbolic-debuginfo/Cargo.toml

All tests still passing on my machine with this bump. This may avoid duplicate crates for consumers of this crate.

Bump the version of wasmparser to the latest version

---

symbolic-minidump/Cargo.toml
symbolic-minidump/build.rs
symbolic-minidump/src/lib.rs
symbolic-minidump/tests/test_processor.rs

This feature flag makes it possible to avoid building and linking breakpad code.

ref: Turn minidump processor (breakpad) into optional feature (NATIVE-524)

---

symbolic-debuginfo/src/wasm/parser.rs

Otherwise the validation would reject otherwise valid wasm files which
use off-by-default features.
This fixes https://github.com/getsentry/sentry-cli/issues/1159

fix: Enable all optional wasm features for validation

---

Makefile
symbolic-debuginfo/src/macho/bcsymbolmap.rs

Previously, the match was truncated to the input buffer length, which meant that
empty files always passed the check, which they obviously should not.

fix: Match the complete BcSymbolMap header (NATIVE-281)

---

symbolic-il2cpp/Cargo.toml
symbolic-il2cpp/src/usym.rs
symbolic-il2cpp/src/usymlite.rs

This starts adding in proper error types for the usym and usymlite parsers with a huge set of overly specific parsing-related members. This should hopefully help us get more useful errors out of the parsers once we start using them.
Minor refactors were also made to each parser's getters as I went through them, but they shouldn't change the existing behaviour of the code.
`anyhow` is still being used by the metadata parser and the dwarf parser in this crate, so it can't be removed yet.
Stacks on top of #527.

feat(usym): Errors for usym[lite] parser

---

symbolic-il2cpp/src/usym.rs

We have types that represent debug IDs and architectures, so instead of returning plain strings for those UsymSymbols now returns those types. 
For the time being, those two fields are lazily converted into their respective types instead of during the parsing phase. I'm working on a different PR that explores the idea of leniently parsing as much of a usym file as possible which will explore the idea of aggressively converting these fields during parsing.
One awkward thing about this new API is that there's currently no way to access the raw debug ID or architecture if they fail to parse. If we feel that it's important to expose these I can explore adding getters for them. They probably won't be particularly useful, though.

ref(usym): Use existing types instead of primitives for fields on UsymSymbols

---

symbolic-common/src/types.rs

This adds C# to the list of languages that can be represented by functions in a symcache and/or functions extracted from various debugging file formats. This is in preparation for usym file parsing, whose entries should use this new language when they're converted into a symcache.

feat(usym): Add C# to the list of languages that can be found in debugging info

---

symbolic-il2cpp/src/usym.rs

Just a simple rename to a field to reflect what we currently do know (or what we think we know) about it so far.

feat(usym): Add in some context on the last field in a record

---

examples/symcache_debug/src/main.rs
symbolic-il2cpp/Cargo.toml
symbolic-il2cpp/src/line_mapping.rs
symbolic-symcache/Cargo.toml
symbolic-symcache/src/new/transform/bcsymbolmap.rs
symbolic-symcache/src/new/transform/il2cpp.rs
symbolic-symcache/src/new/transform/mod.rs

This reverses the dependency `symbolic-il2cpp` has on `symbolic-symcache`, so that the SymCache writer can import structs exposed by `symbolic-il2cpp` without introducing a circular dependency. This will be needed in a future PR when usym to SymCache conversion is introduced.
- `transform.rs` has been moved into its own dedicated directory, and specific `Transformer` implementations have been split off into their own dedicated submodules
- An `il2cpp` feature flag has been added to all of the other crates that integrate il2cpp functionality

ref(symcache): Make symbolic-symcache dependent on symbolic-il2cpp instead of the other way around

---

symbolic-symcache/tests/test_transformers.rs
symbolic-symcache/tests/test_writer.rs

SymCache transformers got their own dedicated module in #538, so they probably should get their own dedicated test module.

ref(symcache): Move transformer tests out to a separate file

---

symbolic-symcache/src/compat.rs
symbolic-symcache/src/lib.rs
symbolic-symcache/src/new/lookup.rs

I'm splitting the work of removing the old symcache into multiple PRs; this is the first. It makes it so that
1. every `SourceLocation` must point to a function and
2. every function must have a valid name.
Both the `process_object` and `process_usym` already work this way, i.e., they should never create a `SourceLocation` without a function or a function without a name. If we nevertheless want to avoid the `unwrap`s, we could return a dummy name/dummy function instead.

ref(symcache): Make functions non-optional

---

symbolic-symcache/src/compat.rs
symbolic-symcache/src/new/error.rs
symbolic-symcache/src/new/mod.rs
symbolic-symcache/src/old/error.rs

This changes the structure of the new symcache errors to the "error struct + error kind enum" pattern. The visibility changes in `new::Error` and `old::SymCacheError` are temporary to make the `From` impl work.

ref(symcache): Change new symcache error structure

---

symbolic-cabi/src/symcache.rs
symbolic-symcache/src/compat.rs
symbolic-symcache/src/new/compat.rs

These methods are obsolete with the new symcache format.

ref(symcache): Remove has_{file,line}_info methods

---

symbolic-debuginfo/Cargo.toml

This just bumps the dependency to wasmparser to version 0.83.0. Tests passed locally.

Bump wasmparser to 0.83.0

---

CHANGELOG.md
symbolic-unreal/src/container.rs

Turns out `scroll` will just throw a `BadOffset` error when you ask it to read 0 bytes.
This should fix https://github.com/getsentry/sentry/issues/34131

fix: Ensure we can parse Unreal4 crashes with 0-length files (ISSUE-1459, ISSUE-1454)

---

examples/symcache_debug/src/main.rs
symbolic-symcache/src/lookup.rs

This adds a `files` method to `SymCache` with behavior analogous to `functions`. It also adds an option to `symcache_debug` to print the files in a symcache. Lastly it improves the documentation on the `{Files,Functions}Debug` structs a bit.

ref(symcache): Add files iterator

---

examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs
symbolic-symcache/src/lib.rs

I got a bit over-motivated and started to rewrite `minidump_stackwalk` based on `symbolic` + `rust_minidump`. The `LocalSymbolProvider` more or less captures the symbol-searching logic of the old implementation, except on demand. There is likely quite a lot of optimization potential in the implementation. Symbolication is also kind of done twice right now; I've experimentally integrated it into the symbol provider, but the old `symbolize` method that ran after stackwalking also still exists. Would be interesting to know how well it works if we remove the latter.

WIP: minidump_stackwalk without breakpad

---

symbolic-cabi/src/symcache.rs
symbolic-symcache/src/lookup.rs
symbolic-symcache/src/raw.rs
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/snapshots/test_cache__lookup.snap

For functions, this simply removes the `comp_dir` field. For files, `comp_dir` is folded into the `directory` field. This increases symcache size because the `comp_dir` part of the directory is duplicated for every different directory.

ref(symcache): Remove comp_dir from files and functions

---

symbolic-symcache/src/lookup.rs

This renames `SourceLocationIter` to `SourceLocations` for the sake of uniformity.

ref(symcache): Rename SourceLocationIter

---

symbolic-minidump/src/cfi.rs
symbolic-minidump/tests/snapshots/test_cfi__cfi_pe_windows.snap

This is trying to fix #546 by more faithfully implementing Win-x64 unwinding, specifically:
It restores all the registers that were saved, and adds support for FP-based unwinding.
I’m still struggling to make this code work correctly with `RtlDispatchException` which we somehow still can’t unwind through.

fix: Make the Win-x64 CFI code more faithful

---

CHANGELOG.md
examples/minidump_stackwalk/Cargo.toml
symbolic-cabi/Cargo.toml
symbolic-cabi/src/core.rs
symbolic-common/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs

This also updates the `wasmparser` dependency, but most importantly debugid/uuid, which constitutes a breaking change.

ref: Update debugid/uuid dependencies

---

symbolic-cabi/Cargo.toml
symbolic-cabi/src/core.rs

This was only imported to downcast/map errors. But this isn’t being used in any other parts of the codebase, so we are mapping errors that we can never create in the first place.

ref: Remove apple-crash-report-parser from symbolic-cabi

---

py/manylinux.sh

see https://github.com/rust-lang/cargo/issues/9167
cargo without this setting uses `libgit2` which appears to have a pretty bad memory leak (consuming ~9GB of ram and then never freeing it) -- later leading to an out-of-memory (docker exits with code 247)
on my x86_64 linux VM emulating arm64 via qemu this reduces the maximum memory usage of the build process from ~13GB to 2.7GB
test run here: https://github.com/getsentry/symbolic/runs/6530937203?check_suite_focus=true

fix(build): use cli git to save some ram with cargo

---

symbolic-cfi/src/lib.rs
symbolic-common/src/types.rs

The `CpuFamily::cfi_register_name` in symbolic-common is only used in `symbolic-cfi`. Therefore, it and its attendant static arrays of register names are moved into that crate.

ref: Move cfi_register_name to symbolic-cfi

---

CHANGELOG.md
symbolic-minidump/src/cfi.rs

Actually there was a comment above the match explaining the intent, but it did not match the actual code.

fix: Only skip one fn when encountering unknown Unwind Codes on Win-x64

---

symbolic-debuginfo/src/dwarf.rs

Some compilers/linkers may use u64::MAX(-1) for the low_pc to indicate deleted / dead code functions. We should just skip over these instead of erroring out hard.

fix: Skip over inverted fn ranges instead of erroring

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/sourcebundle.rs
symbolic-il2cpp/src/line_mapping/from_object.rs
symbolic-il2cpp/src/line_mapping/mod.rs

Il2cpp leaves markers in its generated C++ source to the C# files certain snippets
of code come from. We follow those snippets to also bundle up the C# files they
reference, as we would want to also allow resolving the C# source later on.
The slightly unfortunate bit is that we now read all the files into memory and try to parse them, though hopefully that is not unreasonably slow.

feat: Collect referenced C# file sources

---

symbolic-il2cpp/src/line_mapping/from_object.rs

The parser will now look for the next non-comment line when it encounters a source_info comment and take that as the cpp_line, instead of just taking the source_info comment line itself.

feat: Improve il2cpp line mapping parser

---

.github/workflows/ci.yml
symbolic-symcache/benches/bench_writer.rs

This makes sure that clippy and cargo test also run on benchmarks in CI so they stay up to date with the code.

fix: Fix benchmarks and add them to CI

---

symbolic-debuginfo/src/base.rs

Inspired by https://github.com/getsentry/symbolic/pull/605.

fix: Use saturating add for function end address

---

symbolic-debuginfo/src/dwarf.rs

fixes #606
Thanks for the nice catch @mstange

fix: Correct low/high pc typo

---

examples/symcache_debug/src/main.rs

Without this SetTrue, running the example panics at the end because we try to unwrap a None value.
```
% cargo run --release -p symcache_debug -- -w -d ../dump_syms/testmozglue.txt
Finished release [optimized + debuginfo] target(s) in 0.04s
Running `target/release/symcache_debug -w -d ../dump_syms/testmozglue.txt`
Cache file written to ../dump_syms/testmozglue.txt.symcache
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/symcache_debug/src/main.rs:167:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```rust
// print mode
if *matches.get_one("print_symbols").unwrap() {
println!("{:?}", FunctionsDebug(&symcache));
}
// print mode
if *matches.get_one("print_files").unwrap() { // <-- here
println!("{:?}", …
```

Fix print_files argument of the symcache_debug example.

---

symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/src/lib.rs
symbolic-debuginfo/tests/snapshots/test_objects__breakpad_functions_mac_with_inlines.snap
symbolic-debuginfo/tests/test_objects.rs
symbolic-testutils/fixtures/macos/crash.inlines.sym

Fixes #432.
Please review commits individually.

Add support for parsing breakpad sym files containing INLINE_ORIGIN and INLINE records

---

symbolic-common/src/types.rs
symbolic-debuginfo/src/dwarf.rs

New Rust stable, new clippy warnings in CI. The lint job is currently failing because of unused lifetimes.
This PR fixes one of the three.
There are two more clippy warnings of the same type, but those are in macros and I'm not sure what to do about them.

Remove one unused lifetime

---

examples/addr2line/src/main.rs

This fixes a panic.
I used this example to find discrepancies between native debug files and .sym files, as follows:
```
% cargo run --release -p addr2line -- -Cfi --exe ~/Downloads/libmozglue.dylib.dSYM/Contents/Resources/DWARF/libmozglue.dylib 0x54a7c
[...]
% cargo run --release -p addr2line -- -Cfi --exe ../dump_syms/testmozglue.txt 0x54a7c
[...]
```
It was quite helpful during debugging.

Fix argument name in addr2line example

---

symbolic-debuginfo/tests/snapshots/test_objects__breakpad_functions_mac_with_inlines.snap
symbolic-testutils/fixtures/macos/crash.inlines.sym

The previous test file was generated before I had ironed out all the bugs in dump_syms.
Now that the bugs are fixed, re-generate the test fixture and update the snapshot.
The specific bugs were wrong function names (every inlinee had its parent function's name
instead of its own name) and sometimes wrong file names (I was missing a call to
source.get_true_id).
With the fixed sym file, these snapshots now match even more closely:
test_objects__breakpad_functions_mac_with_inlines.snap
test_objects__mach_functions.snap
Because one file has mangled names and the other one does not, the incorrect
function names can be easy to miss.

Re-generate crash.inlines.sym with correct information

---

symbolic-cfi/src/lib.rs

fixes #618
This needs some testing on real inputs

Emit trivial leaf CFI for UnwindOp::None on arm64

---

symbolic-il2cpp/src/line_mapping/from_object.rs
symbolic-il2cpp/src/line_mapping/mod.rs

Previously, it would return the previous mapping on lookup, even if that is hundreds of lines away.

fix: Only consider "near" lines on il2cpp lookup

---

examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs
symbolic-cfi/src/lib.rs

this is just a hack so far, it needs to be cleaned up so its more reliable, and obviously should only be used when we are dealing with MIPS.

fix: Always generate .ra CFI on MIPS

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/tests/snapshots/test_objects__pdb_functions.snap
symbolic-debuginfo/tests/test_objects.rs

This replaces symbolic's TypeFormatter with the one from the pdb_addr2line
crate, which is more fully-featured. Most importantly, it supports
function arguments, both for inlined functions (which use IdIndex) and
for procedures (which use TypeIndex).
Fixes #423.
As a consequence of this commit, function names for procedures from PDBs
will now always contain arguments. These arguments are obtained from the
type data, and not from demangling. Consequently, their presence is
unaffected by demangler flags, and users cannot opt out of the arguments.
Similarly, we never print the return type, and there is no way for users
to opt in to showing the return type.
This commit also moves some things related to ModuleInfo loading around.
This was needed to make the lifetimes work out successfully. …

Use pdb_addr2line::TypeFormatter.

---

symbolic-debuginfo/src/pdb.rs

SeparatedCode symbols usually directly follow their associated Procedure
symbol. They describe a part of the function that has been extracted out
and moved to a separate place. They come with their own set of line
information and can be treated very similarly to regular functions.
The impact of this patch can be tested on a combase.pdb from the
Microsoft symbol server:
```
% curl -o combase.pdb -L "https://msdl.microsoft.com/download/symbols/combase.pdb/071849A7C75FD246A3367704EE1CA85B1/combase.pdb"
% cargo run --release -p symcache_debug -- --report -d combase.pdb
% cargo run --release -p addr2line -- -Cfi -e combase.pdb 0x1a147c
```
Before this patch:
```
% cargo run -p addr2line -- -Cfi -e combase.pdb 0x1a147c
Containers::Intrusive::Details::HashTableBase<class std::tuple<class …
```

Add support for SeparatedCode symbols.

---

symbolic-ppdb/src/format/sequence_points.rs

Addition crashes on overflow in debug builds. I think using `saturating_add` is clearest here.

fix(ppdb): Use saturating addition

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/pdb.rs

- The updated crate can correctly deal with missing type references
- We now swallow errors, falling back to the mangled names
This is rolling forward and a better alternative to #631

fix: Update pdb-addr2line TypeFormatter

---

symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/tests/snapshots/test_objects__breakpad_functions_mac_with_inlines.snap
symbolic-debuginfo/tests/snapshots/test_objects__elf_functions.snap
symbolic-debuginfo/tests/snapshots/test_objects__mach_functions.snap
symbolic-symcache/tests/test_writer.rs

Consider the following code:
```
| fn parent() {
1 |   child1();
2 |   child2();
| }
1 | fn child1() { child2() }
1 | fn child2() {}
```
we assume here that we transitively inline `child2` all the way into `parent`.
but we only have a single line record for that whole chunk of code,
even though the inlining hierarchy specifies two different call sites
```
addr:    0x10 0x20 0x30 0x40 0x50
v    v    v    v    v
parent:  |-------------------|
child1:       |----|           (called from parent.c line 1)
child2:       |----|           (called from child1.c line 1)
|----|      (called from parent.c line 2)
|----|         |----| (parent.c line 1)
|---------|      (child2.c line 1)
```

ref: Split DWARF line records according to inlinees

---

symbolic-debuginfo/src/pdb.rs

For example we have observed in a real-world pdb that has:
- A function 0x33ea50 (size 0xc)
- With one line record: 0x33e850 (size 0x26)
The line record is completely outside the range of the function.

fix: Sanitize collected lines in PDB parsing

---

symbolic-debuginfo/src/pdb.rs

Instead of checking symbol.function, check whether the symbol is contained
in an executable section. This matches what pdb-addr2line does, and is
closer to what dump_syms' handwritten PDB parsing does.
This change allows more symbols to be included. For example, it allows the
following symbols from basic-opt32.pdb to pass the check:
```
4f9d7 _rtinfpopse
4f9d9 _rtinfnpopse
4f9e9 _fFLN
4fa9e _rtinfpop
4faa0 _rtinfnpop
4fabd _ffexpm1
```
https://github.com/mozilla/dump_syms/blob/54f9e6240e34cf17fc7dc60ac4985772e2c20001/test_data/windows/basic-opt32.pdb
These symbols have symbol.function == false, so they were being filtered
out before.
The change also adds over 300 symbols for ntdll.pdb BD298DA990CD4BF9BE5CE4796D7924C61.
The handwritten PDB parsing in dump_syms currently uses this full …

fix(debuginfo): include more pdb symbols

---

symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/tests/snapshots/test_objects__pdb_symbols.snap

Leaving the symbol name in its original form allows consumers to detect
"C decorated" functions correctly.
According to the Microsoft documentation [1], there are four forms of
"C decorated" names:
```
_<name> (cdecl)
_<name>@<paramsize> (stdcall)
@<name>@<paramsize> (fastcall)
<name>@@<paramsize> (vectorcall)
```
According to the same docs, the first three are only used on 32 bit. [2]
dump_syms parses these forms and decodes the parameter size from them.
It needs the parameter size on 32 bit for correct stack unwinding in
some cases.
Before this patch, symbolic-debuginfo was stripping leading underscores
from these symbols. This made it impossible for dump_syms to detect the
second form (stdcall, `_<name>@<paramsize>`), so it couldn't decode the
parameter size from it and would leave the …

fix(debuginfo): don't strip leading underscores from PDB symbols

---

symbolic-demangle/src/lib.rs
symbolic-demangle/tests/test_msvc.rs

These flags create more visually pleasing results for function names
which are demangled from the MSVC mangling scheme.
Here are two examples from oleaut32.pdb A128178EA85DAE837E96C39303FF06381:
Before: `SafeGetLocaleInfoPooled(struct tagDATEINFO *,unsigned long,unsigned short * *,int *)`
After: `SafeGetLocaleInfoPooled(tagDATEINFO*, unsigned long, unsigned short**, int*)`
Before: `CTypeInfo2::Invoke(void *,long,unsigned short,struct tagDISPPARAMS *,struct tagVARIANT *,struct tagEXCEPINFO *,unsigned int *)`
After: `CTypeInfo2::Invoke(void*, long, unsigned short, tagDISPPARAMS*, tagVARIANT*, tagEXCEPINFO*, unsigned int*)`
The flags in detail:
* `SPACE_AFTER_COMMA`: Adds a space after each comma.
* `HUG_TYPE`: Removes the space in front of "*" and "&".
* `NO_CLASS_TYPE`: Removes "struct" / …

fix(demangle): tweak MSVC demangling flags

---

symbolic-cfi/src/lib.rs
symbolic-cfi/tests/snapshots/test_cfi__cfi_pe_windows.snap

We have seen some SaveNonVolatile unwind operations underflow the current stack frame, so they are saving/loading registers into the callers stack frame.
For example `VCRUNTIME140.dll!__C_specific_handler` can do this.
Its full Unwind Operations look like this:
```
Function Table:
Start Address: 0xbff0
End Address: 0xc1eb
Unwind Info Address: 0x10138
Version: 1
Flags: 0
Size of prolog: 28
Number of Codes: 12
No frame pointer used
Unwind Codes:
0x1c: UOP_SaveNonVol RSI [0x0080]
0x1c: UOP_SaveNonVol RBP [0x0078]
0x1c: UOP_SaveNonVol RBX [0x0070]
0x1c: UOP_AllocSmall 64
0x18: UOP_PushNonVol R15
0x16: UOP_PushNonVol R14
0x14: UOP_PushNonVol R13
0x12: UOP_PushNonVol R12
0x10: UOP_PushNonVol RDI
```
We previously used saturating_sub to clamp these offsets to 0, meaning things are loaded from …

fix: Allow Windows CFI to underflow

---

symbolic-symcache/src/writer.rs
symbolic-symcache/tests/test_writer.rs

This fixes #646 and #647. I think it's also simpler; we iterate over the inlinees twice, but at least the responsibility of who inserts what range is clear now.
Overall it's about 50 more lines of code, but those extra lines are just comments.
Commit message for the squashed commit:
```
fix(symcache): Rework the symcache writer for correctness
This commit also reverts the public API
`SymCacheConverter::process_symbolic_function` back to its 9.0.0 signature.
Fixes #646.
Fixes #647.
Before this fix, for each function in the inlinee tree we inserted an entry
into `self.ranges` for every line address. These entries were overwritten
repeatedly as we descendent into the inlinees.
Now we just insert entries for address ranges which are not covered by
the function's inlinees. And we no longer …
```

Rework the symcache writer for correctness

---

symbolic-debuginfo/src/dwarf.rs

This fix turned out to be less safe than initially thought, so tweak the comment.

docs(debuginfo): adjust comment about "safely skipping" things

---

symbolic-debuginfo/src/dwarf.rs

We were correctly handling `DebugAddrIndex` attributes, but never provided the `.debug_addr` section they are based on, so resolving those indices always failed.
Fixes https://github.com/getsentry/symbolicator/issues/855
Fixes https://getsentry.atlassian.net/browse/ISSUE-1563

fix: Correctly use DWARF5 .debug_addr section

---

examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs

We are dealing with a PE file that does not have a CodeView record / DebugId,
in which case we should still be able to use it based on its CodeId.

ref: Use CFI for modules that only have a CodeId

---

examples/symcache_debug/src/main.rs
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/test_writer.rs

https://github.com/getsentry/symbolic/pull/642 removed stripping the underscores from C-decorated Windows symbols.
The `symbolic-debuginfo` abstraction now outputs raw names (except for mach-o, where it still strips underscores).
As a followup to this change, this will now undecorate these symbols when writing a symcache.

fix: Undecorate Windows Symbols in SymCache

---

symbolic-cfi/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-unreal/Cargo.toml

`1.18.0` added a warning for future `yaml` and `json` assertions deprecation, which makes our builds fail, as we use `-Dwarnings` flag in the CI.

deps: Update insta to 1.18.0 and enable its yaml feature

---

examples/smcache_debug/src/main.rs
symbolic-smcache/src/smcache/writer.rs
symbolic-smcache/src/source.rs

The SourceContext is responsible to offer fast byte offset <-> line/column
conversion. Previously it was based on saving the offset of each line
and doing a byte/utf16-offset counting loop. Turns out this is not a
good idea if you never have line breaks like in the case of minified js.
Instead, this now creates an index every X chars and rather goes from there.
This cuts total "create/write SmCache" more than in half, and the
previous "resolve original names" and "convert scope index" spans that
do a lot of conversions down by 1-2 orders of magnitude.

fix: Speed up the SmCache SourceContext

---

symbolic-sourcemapcache/Cargo.toml
symbolic-sourcemapcache/src/sourcemapcache/mod.rs
symbolic-sourcemapcache/src/sourcemapcache/writer.rs
symbolic-sourcemapcache/tests/integration.rs

The Metro/Hermes SourceMaps have scopes embedded in them which we now prefer.
In that case, we can completely skip parsing and extracting scopes from the minified JS.
This depends on having https://github.com/getsentry/rust-sourcemap/pull/48 in a published release.

ref: Skip parsing Minified Source when dealing with Metro/Hermes

---

symbolic-cfi/src/lib.rs

The reason for our _sigtramp workaround is lack of support for DWARF expressions.
This fact is documented in more detail, and the hand-crafted ASCII CFI is extended to
all the call preserved (callee saves) registers.

ref: Improve _sigtramp workaround and explanation

---

symbolic-sourcemapcache/src/sourcemapcache/lookup.rs
symbolic-sourcemapcache/src/sourcemapcache/raw.rs
symbolic-sourcemapcache/src/sourcemapcache/writer.rs
symbolic-sourcemapcache/tests/integration.rs

This addition will give us the original column line number, which we need to preserve current functionality.

feat: Add column getter to SourceLocation lookup struct

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs

Unfortunately there doesn't seem to be any changelog file for wasmparser, but API changes are quite limited here.

Bump wasmparser to 0.89.1

---

symbolic-sourcemapcache/src/sourcemapcache/lookup.rs
symbolic-sourcemapcache/src/sourcemapcache/writer.rs

This changes the logic of line offsets as follows: each file has one line offset at the start and then one after every line, no exceptions. In particular, this means that an empty file has one line offset and a file ending with on a newline has a line offset for the final empty line. The tests should illustrate fairly clearly how it works.
Since files don't have a line offset for the end of the file anymore, the logic of `File::line` changes as well, but this is straightforward: if there is a next line offset, we slice until that offset, and if there isn't, we just slice until the end of the file.
I've gotta say I don't love the implementation of `SourceMapCacheWriter::line_offsets`, I think this madcap chaining of iterators is hard to read. But I can't really think of a better way to do …

fix(sourcemapcache): Correct line offsets

---

symbolic-debuginfo/src/dwarf.rs

The value of the `DW_AT_producer` attribute may be a reference into the `debug_str` section of the DWARF file, a case we failed to handle. This correctly resolves the attribute's value.
Fixes #675.

fix(debuginfo/dwarf): Correctly resolve DW_AT_producer

---

CHANGELOG.md
symbolic-demangle/src/lib.rs
symbolic-demangle/tests/test_cpp.rs

The underlying `cpp_demangle` crate is a bit too lenient and accepts bare types, turning `a` into `signed char` for example. We want to be more strict and instead only accept `_Z` prefixed mangled names.

fix: Be more strict when demangling C++ names

---

CHANGELOG.md
symbolic-debuginfo/src/dwarf.rs

Abbreviations in the debug_abbrev section can be, and often are, shared between compilation units. However, the upstream `gimli::Unit::new` eagerly parses and allocates `Abbreviations` for each `Unit`.
We have a pathological case where an extremely large 5.5G DWARF file with ~280k compilation units and ~1500 Abbreviations is taking a very long time to process and is holding on to an unreasonable amount of memory while doing so.
Profiling suggests a majority of time and memory is spent parsing and dropping these Abbreviations.
This workaround copies the `gimli::Unit::new` code to avoid parsing `Abbreviations` at offset 0. In the pathological case mentioned above, *all* the compilation units share the same list of `Abbreviations` at offset 0.
Runtime of symcache conversion for the mentioned …

ref: Work around gimli re-parsing Abbreviations

---

Cargo.toml
examples/addr2line/Cargo.toml
examples/dump_cfi/Cargo.toml
examples/dump_sources/Cargo.toml
examples/minidump_stackwalk/Cargo.toml
examples/object_debug/Cargo.toml
examples/symcache_debug/Cargo.toml
examples/unreal_engine_crash/Cargo.toml
symbolic-cabi/Cargo.toml
symbolic-cfi/Cargo.toml
symbolic-common/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/fuzz/Cargo.toml
symbolic-demangle/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-symcache/src/lookup.rs
symbolic-testutils/Cargo.toml
symbolic-unreal/Cargo.toml
symbolic/Cargo.toml

I was actually surprised that we were still on Rust 2018 here.

ref: Update deps and switch to Rust 2021

---

CHANGELOG.md
symbolic-debuginfo/src/dwarf.rs

The recent fix for Abbreviations parsing might have been too overeager and may cause EOF errors in case there are no Abbreviations (at offset 0) at all.

fix: Be more lenient parsing Abbreviations

---

.github/workflows/build.yml

NOTE: Move to `manylinux_2_28` and drop `manylinux_2_28_i686` in the next major.

ci: Bump docker builds to manylinux2014

---

CHANGELOG.md
symbolic-cabi/include/symbolic.h

I thought we do it during publishing 😔

fix: Rebuild C headers for smcache to expose token name

---

examples/symcache_debug/src/main.rs
symbolic-cfi/src/lib.rs
symbolic-common/src/byteview.rs
symbolic-symcache/src/writer.rs
symbolic-unreal/Cargo.toml

Update the `anylog` crate to 0.6.3 with fix from https://github.com/getsentry/rust-anylog/pull/7 which caused panic in some cases of parsing and creating the dates.

chore: Update anylog to 0.6.3

---

.vscode/extensions.json

The old rust-analyzer extension has been removed from the VS Code market place, so VS Code now displays a warning when the symbolic repo is opened in the editor. This fixes that warning.
The file indentation has changed because it seems that this is the first time anybody has touched this file since editor.formatOnSave was turned on.

Fix rust-analyzer extension ID.

---

symbolic-cabi/Cargo.toml
symbolic-cabi/src/sourcemapcache.rs

Instead of holding the SourceMapCache buffer in memory when it is being used via the cabi/python bindings, write it to a tempfile which is automatically cleaned up when the SourceMapCache is dropped.
This should reduce memory pressure and allow the OS to page that out.

fix: Write SourceMapCache to disk in cabi

---

symbolic-sourcemapcache/Cargo.toml

Fixes off-by-one issue https://github.com/getsentry/js-source-scopes/pull/15/

deps: Update js-source-scopes to 0.2.2

---

examples/debuginfo_debug/Cargo.toml
examples/debuginfo_debug/src/main.rs

This example prints out the parsed debuginfo Function tree in a similar format to the snapshot tests in test_objects. (The only difference is that this also prints the end address for each line.)
It also performs some consistency checks.
Those checks should make it easier to ensure that all our parsers are creating debuginfo with the shape that the consumers (symcache writer and dump_syms) expect.
You can run it as follows:
`cargo run --release -p debuginfo_debug -- symbolic-testutils/fixtures/macos/crash.dSYM/Contents/Resources/DWARF/crash`

Add a debuginfo_debug example

---

symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/tests/snapshots/test_objects__elf_functions.snap
symbolic-debuginfo/tests/test_objects.rs
symbolic-symcache/tests/test_writer.rs
symbolic-testutils/fixtures/macos/crash.inlines.sym

Fixes #713.
In the FunctionBuilder, which is used for the DWARF reader and for the breakpad reader, we were already splitting lines which were extending beyond the end of an inlinee. Now we also split lines which extend into the beginning of the next inlinee.
This fixes all "overlapping line" warnings in the debuginfo_debug example when run on the macos/crash.dSYM. Those overlapping lines were caused by "self lines" which overlapped with "inlinee lines".
I've also updated crash.inlines.sym with a file that I freshly generated using a dump_syms build which includes this symbolic fix. Now the crash.inlines.sym file no longer has overlapping inlinees.

fix(debuginfo): Split lines in more cases.

---

examples/debuginfo_debug/src/main.rs
symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/tests/snapshots/test_objects__elf_functions.snap
symbolic-debuginfo/tests/test_objects.rs
symbolic-symcache/tests/test_writer.rs
symbolic-testutils/fixtures/macos/crash.inlines.sym

This commit adds a few checks to the debuginfo_debug example: We now check that the lines from sibling inlinees don't overlap with each other.
This is another failure case which is currently happening in practice, namely in the breakpad reader, and it's confusing the symcache writer. I will fix the breakpad reader in a different PR.

 feat(debuginfo): Add inlinee overlap checks.

---

symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/tests/test_objects.rs

 fix(debuginfo): Ensure proper inlinee nesting.

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/weekly.yml
symbolic-ppdb/src/format/metadata.rs
symbolic-ppdb/src/format/streams.rs
symbolic-symcache/src/writer.rs

- Switches to newest actions versions, except for `actions-rs/audit-check`.
- We are not using submodules anymore.
- Switches Code Coverage action to `cargo-llvm-cov`.

ci: Update CI workflows

---

symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/function_builder.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/ppdb.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-debuginfo/tests/snapshots/test_objects__ppdb_files.snap
symbolic-debuginfo/tests/test_objects.rs
symbolic-ppdb/src/format/mod.rs
symbolic-ppdb/src/format/sequence_points.rs
symbolic-symcache/tests/test_writer.rs

feat: Portable PDB source files list

---

.github/workflows/build.yml
Makefile
py/manylinux.sh
py/manylinux_aarch64.sh

This is a replacement draft for #699. Differences are:
* it doesn't change the existing workflows for `i686` and `x86_64` 
* it introduces a minor conditional on the path from the GHA to the `aarch64`-specific build-script
* the `aarch64`-specific build script is run in a minimal cross-compilation container which provides
* a `manylinux2014` compatible cross-compilation toolchain (which can be easily switched to manylinux_2_28 if needed)
* a `pypa manylinux` environment
* the build script differs from the normal build script in that
* it must build `libffi` with the cross-compilation toolchain
* sets up a python `crossenv` so we don't have to load and start yet another container to build the` aarch64` wheel

Use cross-compilation for aarch64 release-build

---

.github/workflows/ci.yml
.github/workflows/weekly.yml
examples/minidump_stackwalk/src/main.rs
symbolic-ppdb/src/lib.rs

Fix nightly clippy lints
Runs CI on `--all-targets` and `--doc` separately, as you can’t mix those two :-(

Fix clippy and doctests

---

CHANGELOG.md
symbolic-cabi/src/sourcemapcache.rs
symbolic-sourcemapcache/Cargo.toml
symbolic-sourcemapcache/src/lookup.rs

This simplifies the usage for self-referential data, where `SelfCell` is required and allows us to remove the unnecessary wrapper from cabi and in the future from symbolicator.

ref(sourcemapcache): Implement AsSelf for SourceMapCache

---

CHANGELOG.md
symbolic-debuginfo/src/function_builder.rs

As described in https://github.com/getsentry/symbolic/issues/746, broken Breakpad files sometimes contain line records that start before the function they supposedly belong to. This PR discards those records when parsing functions. It also does the same for inlinees, although we haven't actually seen this happen.
Should we report this to the user somehow or is it ok to discard the records silently?

fix: Discard invalid line records and inlinees

---

README.md

Should we point out Unity's IL2CPP support on the README too somehow?

chore(ppdb): add to readme

---

examples/sourcemapcache_debug/src/main.rs

Mostly to ease debugging with our support team.

ref(smcache): Add context lines and source printing to our example

---

CHANGELOG.md
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/tests/test_objects.rs
symbolic-ppdb/tests/test_ppdb.rs

feat: PE embedded PPDB decompression to a custom writer

---

CHANGELOG.md
symbolic-debuginfo/tests/test_objects.rs
symbolic-ppdb/src/format/mod.rs
symbolic-ppdb/tests/test_ppdb.rs

Ppdb parsing incorrectly assumed that the `#Pdb` stream would always be physically located before the `#~` stream and just parsed them in order. Since the `#Pdb` stream contains table size information that must be known during `#~` parsing, this led to the bug described in #759.
The fix is simply to initially collect the locations of all the streams and then parse the `#Pdb` stream before the others.

fix(ppdb): Parse streams in the correct order

---

CHANGELOG.md
symbolic-debuginfo/src/sourcebundle.rs

Part of https://github.com/getsentry/sentry-cli/issues/1482
This enables Sentry-CLI to filter out embedded sources while collecting referenced files.

feat: change `SourceBundleWriter::write_object_with_filter()` filter callback to take `SourceCode`

---

CHANGELOG.md
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/object.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/ppdb.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-debuginfo/tests/test_objects.rs

This adds a new header `debug-id` to files stored in a source bundle that is used as artifact bundle. The goal of this is to enable the lookup of JavaScript files by debug ID. As we are not using much of the `DebugSession` abstraction for this yet, i chose not to add this to the trait but just the particular implementation of a session for source bundles. Lookup requires knowledge of the file type and only returns contents, no meta information.
```rust
let sess = bundle.debug_session().unwrap();
let f = sess
.source_by_debug_id(
"5e618b9f-54a9-4389-b196-519819dd7c47".parse().unwrap(),
SourceFileType::MinifiedSource,
)
.unwrap()
.expect("should exist");
```
The manifest gains a new well known key in the `headers` dictionary called `debug-id` which so far is exclusively used to refer to …

feat: Added debug IDs to source bundle javascript files

---

CHANGELOG.md
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/js.rs
symbolic-debuginfo/src/lib.rs
symbolic-debuginfo/src/sourcebundle.rs

This adds support for parsing `debugId` references in the source file. It also provides utilities for parsing the comments separately so that code does not need to be written another time in other places.
Followup to #762
Refs https://github.com/getsentry/sentry-cli/pull/1469

feat: Add support for embedded debug IDs in minified files

---

CHANGELOG.md

Some changelog entries were referring to the introduction of a `SourceCode` enum that has since been replaced with `SourceFileDescriptor`.

meta: Correct changelog

---

CHANGELOG.md
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/ppdb.rs
symbolic-debuginfo/src/sourcebundle.rs

This replaces all usages of `LazyCell` (which is not thread safe) with `OnceCell`, which is and will also be available as `std::sync::OnceLock` in the future.

ref: Make `SourceBundleDebugSession`: `Send`, `Sync` and `AsSelf`

---

CHANGELOG.md
symbolic-ppdb/src/cache/writer.rs

It is a bit unclear how to really treat these hidden sequence points.
However just setting the line to `0` means we do find a source location (with line `0`) on lookup, and then later on we apply the wrong source context lines.
By ignoring these, we do get the correct source line (and thus source context) for the linked customer issue.
If just skipping these is really the way we want to go:
fixes https://github.com/getsentry/symbolic/issues/768
fixes https://github.com/getsentry/team-stacktrace-private/issues/28

fix: Completely skip over hidden sequence points

---

symbolic-cabi/Cargo.toml
symbolic-cfi/Cargo.toml
symbolic-common/Cargo.toml
symbolic-common/src/types.rs
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs
symbolic-demangle/Cargo.toml
symbolic-il2cpp/Cargo.toml
symbolic-ppdb/Cargo.toml
symbolic-sourcemapcache/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-unreal/Cargo.toml
symbolic-unreal/src/context.rs
symbolic-unreal/src/logs.rs

It is pretty much impossible to tell what the "real" minimum version of a dependency is, so bump them all to the very latest.
Also updates `wasmparser`, which is always a pain as it has frequent undocumented API changes :-(
fixes https://github.com/getsentry/symbolic/issues/770

Bump dependencies to latest versions

---

symbolic-cabi/Cargo.toml

5.0.1 contains some performance optimizations.

chore(deps): Bump proguard version to 5.0.1

---

CHANGELOG.md
symbolic-debuginfo/src/sourcebundle.rs

The default ZipWriter/FileOptions is using the current timestamp depending on feature flags. Now we explicitly default to a deterministic timestamp for files.
I verified locally that this fixes https://github.com/getsentry/sentry-cli/issues/831 🎉

Make SourceBundle writer deterministic

---

symbolic-debuginfo/src/elf.rs

Support reading Playstation DebugId and Object Kind

---

CHANGELOG.md
symbolic-debuginfo/src/sourcebundle.rs

This gives each `SourceBundleDebugSession` its own `archive`, so multiple sessions do not contend on the same lock. Also creates the manifest index eagerly and shares that across debug sessions. While previously the complete `SourceBundle` was cached in memory and shared, each `DebugSession` would still create its own index on each access. Another driveby improvement is to provide a consuming `SourceFileDescriptor::into_contents` to avoid a clone.

Optimze SourceBundle/DebugSession

---

CHANGELOG.md
symbolic-sourcemapcache/src/writer.rs

We have seen cases in Flutter where a scope name cannot be resolved, but the scope's closing brace has the correct name attached. Therefore, if we can't resolve a scope name the straightforward way, we try to grab the name off the scope's last token.

fix(sourcemap): Improve scope name resolution

---

symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs

It is used only in one place, and an in-crate definition is simple enough.
We are using `symbolic` and are auditing our third-party crates. To reduce the audit surface of `symbolic`, this removes `bitvec` and replaces it with an implementation that should be as performant. `bitvec` is a huge crate, so it is preferable to remove it since it is barely used.
If this is not desirable, we can also patch `bitvec` with an API-equivalent interface on our side, but that is an uglier solution and may be more burdensome in the future.

Remove the bitvec crate.

---

examples/minidump_stackwalk/Cargo.toml
examples/minidump_stackwalk/src/main.rs

This gets rid of the unmaintained `encoding` dependency.

chore(deps): Bump minidump to 0.16.0

---

symbolic-cabi/Cargo.toml
symbolic-sourcemapcache/Cargo.toml

`5.0.2` of https://github.com/getsentry/rust-proguard contains a fix for wrong line numbers when using callbacks like `setOnMenuItemClickListener`.

chore(deps): Bump proguard to `5.0.2`

---

scripts/bump-version

Looks like `minidump-processor` is now using symbolic as well. And we cannot bump the version of its symbolic dependency because its an out-of-workspace package. `cargo update` in that case would require the version to already exist in the registry.
Just remove the `cargo update`. We do not check in our lockfile so whatever updates it would do would never be committed anyway.

Remove `cargo update` from version-bump script

---

symbolic-debuginfo/src/lib.rs

At https://docs.rs/symbolic/latest/symbolic/debuginfo/index.html, if you click "object crate", it goes to the wrong page.

(Super tiny PR) Fix wrong link

---

CHANGELOG.md
symbolic-cabi/src/sourcemap.rs
symbolic-common/Cargo.toml
symbolic-common/src/lib.rs
symbolic-common/src/sourcelinks.rs
symbolic-ppdb/Cargo.toml
symbolic-ppdb/src/format/mod.rs
symbolic-ppdb/src/format/sourcelinks.rs

In preparation of using sourcelinks in sourcebundles, this extracts the sourcelink functionality from `symbolic-ppdb` and moves it to `symbolic-common`. It also refactors the implementation based on `serde`.
The JSON representation of a `SourceLinkMappings` struct looks like this:
```
{
"C:\\src\\*":                   "http://MyDefaultDomain.com/src/*",
"C:\\src\\fOO\\*":              "http://MyFooDomain.com/src/*",
"C:\\src\\foo\\specific.txt":   "http://MySpecificFoodDomain.com/src/specific.txt",
"C:\\src\\bar\\*":              "http://MyBarDomain.com/src/*",
"C:\\src\\file.txt": "https://example.com/file.txt",
"/home/user/src/*": "https://linux.com/*"
}
```
One downside of this is that it makes the `serde` dependency of `symbolic-common` non-optional. I don't know how big a deal this …

ref: Move sourcelinks to symbolic-common

---

symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-symcache/src/transform/bcsymbolmap.rs

fix: Clippy

---

CHANGELOG.md
Cargo.lock
symbolic-debuginfo/src/sourcebundle.rs

Sourcebundle manifests written after the introduction of source links would always contain a `source_links: {}` field, which would cause earlier `symbolic` versions to throw an error when trying to read the manifest (because `source_links` is interpreted as a key in the `attributes` map, whose values are supposed to be strings).
This fixes the problem by not writing empty source link maps (which is all that we are seeing in the wild) at all.

fix(sourcebundles): Don't write empty sourcelinks

---

CHANGELOG.md
Cargo.lock
symbolic-cfi/src/lib.rs

PE files reference their corresponding debug file via name and DebugId. We can put these in a CfiCache `MODULE` entry to be able to backfill a missing DebugFile/DebugId in a minidump.
Companion PR: https://github.com/getsentry/symbolicator/pull/1305

Emit a MODULE record for PE files

---

CHANGELOG.md
Cargo.lock
py/symbolic/proguard.py
symbolic-cabi/include/symbolic.h
symbolic-cabi/src/proguard.rs

Use a specific boolean flag to decide whether to deobfuscate based on parameters list or line numbers.
Empty parameters list should not be used to make this discrimination, but at the same Time `Option<T>` type is not FFI safe therefore we cannot use it for the Rust bindings.

fix empty parameters list issue

---

CHANGELOG.md
Cargo.lock
examples/minidump_stackwalk/Cargo.toml
symbolic-common/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/src/wasm/parser.rs
symbolic-sourcemapcache/Cargo.toml

In particular, this updates to `gimli:0.28.1`, which needes a manual `populate_abbreviations_cache` call to retain the current performance it has (aka, not OOM after spending a ton of time parsing duplicated abbreviations).
As well as the usual churn related to `wasmparser`.

Update crate dependencies

---

CHANGELOG.md
Cargo.lock
py/symbolic/proguard.py
symbolic-cabi/Cargo.toml
symbolic-cabi/include/symbolic.h
symbolic-cabi/src/proguard.rs

This follow the changes in https://github.com/getsentry/rust-proguard/pull/34
This will allow us to make `mappings_by_params` initialization optional so that we don't incur in unnecessary memory increase in those part of sentry services where deobfuscation based on parameters list instead of line numbers is not necessary.

enhance: make mapping by params initialization optional (android deobfuscation)

---

CHANGELOG.md
symbolic-debuginfo/src/pe.rs

Do not assume that the debug file string is as long as the array in which it is stored

---

symbolic-debuginfo/src/sourcebundle.rs

`source_by_zip_path` does not need to return an `Option`

---

Cargo.lock
symbolic-cfi/src/lib.rs
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/breakpad.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/pdb.rs
symbolic-debuginfo/src/pe.rs
symbolic-debuginfo/src/sourcebundle.rs
symbolic-demangle/src/lib.rs
symbolic-ppdb/src/format/metadata.rs
symbolic-symcache/src/lib.rs
symbolic-unreal/src/logs.rs

This is still holding off on updating the `sourcemap` dependency, as we would probably have to bump that in `js-source-scopes` first.

Apply `clippy` lints, and do a `cargo update`

---

CHANGELOG.md
examples/minidump_stackwalk/Cargo.toml

Fixes https://github.com/getsentry/symbolic/issues/832

chore: update tokio to latest version

---

CHANGELOG.md
symbolic-debuginfo/src/dwarf.rs

**Background**
If there is an indirect self-reference, infinite recursion can occur.
**Changes**
* keep track if the prior entry is the same as the next entry to go to and skip function name resolution
**Test Plan**
* tested against a symbol file where this was occurring and it no longer crashes

Avoid infinite recursion on indirect self-references

---

CHANGELOG.md
Cargo.toml
examples/addr2line/Cargo.toml
examples/debuginfo_debug/Cargo.toml
examples/dump_cfi/Cargo.toml
examples/dump_sources/Cargo.toml
examples/minidump_stackwalk/Cargo.toml
examples/object_debug/Cargo.toml
examples/sourcemapcache_debug/Cargo.toml
examples/symcache_debug/Cargo.toml
examples/unreal_engine_crash/Cargo.toml
symbolic-cabi/Cargo.toml
symbolic-cfi/Cargo.toml
symbolic-common/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-demangle/Cargo.toml
symbolic-il2cpp/Cargo.toml
symbolic-ppdb/Cargo.toml
symbolic-sourcemapcache/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-unreal/Cargo.toml
symbolic/Cargo.toml

This bundles all dependency versions together in the main `Cargo.toml`.

meta: Switch to workspace dependencies

---

Cargo.lock
Cargo.toml
symbolic-cfi/src/lib.rs
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs

This also includes `gimli` and `wasmparser` changes.
---
Will rebase once https://github.com/getsentry/symbolic/pull/839 lands.

Do a `cargo update`

---

Cargo.lock
Cargo.toml
examples/sourcemapcache_debug/Cargo.toml
symbolic-symcache/Cargo.toml

I've given @boshen 's cargo-shear a try: https://github.com/Boshen/cargo-shear

chore: remove unused dependencies

---

Cargo.lock
Cargo.toml
symbolic-cabi/src/sourcemap.rs

We should really start moving `cabi` stuff to `ophio`, and eventually remove things from the `symbolic` repo.

Update `sourcemapcache` dependencies

---

Cargo.lock
Cargo.toml
examples/addr2line/Cargo.toml
examples/debuginfo_debug/Cargo.toml
examples/dump_cfi/Cargo.toml
examples/dump_sources/Cargo.toml
examples/minidump_stackwalk/Cargo.toml
examples/object_debug/Cargo.toml
examples/sourcemapcache_debug/Cargo.toml
examples/symcache_debug/Cargo.toml
examples/unreal_engine_crash/Cargo.toml
symbolic-cabi/Cargo.toml
symbolic-cfi/Cargo.toml
symbolic-common/Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-demangle/Cargo.toml
symbolic-il2cpp/Cargo.toml
symbolic-ppdb/Cargo.toml
symbolic-sourcemapcache/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-unreal/Cargo.toml
symbolic/Cargo.toml

A recent publish with craft failed because it claims "Circular dependency detected!". This is most likely caused by the recent change to using workspace dependency inheritance, and lack thereof within craft.
So just revert this change, to hopefully make craft happy.

Revert workspace inheritance for workspace deps

---

CHANGELOG.md
Cargo.lock
Cargo.toml

The recent symbolicator update started emitting errors related to this. After a short debugging sessions, I pinned down the problem to a regression in `zip` which broke archives with >64k files.
See https://github.com/zip-rs/zip2/issues/189 which is also linked from the `Cargo.toml`.

Downgrade and pin `zip` to fix SourceBundles with >64k files

---

Cargo.lock
examples/symcache_debug/src/main.rs
symbolic-cfi/src/lib.rs
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/elf.rs
symbolic-debuginfo/src/macho/compact.rs
symbolic-debuginfo/src/pdb.rs

Fix nightly clippy lints

---

CHANGELOG.md
Cargo.lock
Cargo.toml
symbolic-debuginfo/src/wasm/parser.rs

The main reason for the upgrade is to improve these two reports:
* https://github.com/getsentry/symbolic/issues/848
* https://github.com/bytecodealliance/wasm-tools/pull/1650
* https://github.com/getsentry/symbolic/issues/850
* https://github.com/bytecodealliance/wasm-tools/pull/1661

Updated wasmparser dependency to 0.214.0

---

CHANGELOG.md
symbolic-debuginfo/src/sourcebundle.rs

fix(sourcebundles): Skip invalid sources

---

CHANGELOG.md
symbolic-debuginfo/src/sourcebundle.rs

Add a callback to SourceBundleWriter that is called every time we skip adding a file to the bundle due to a ReadFailed error.
Also, https://github.com/getsentry/symbolic/pull/861 missed another spot where the ReadFailed error can cause the write function to fail; this PR fixes that.
Closes https://github.com/getsentry/symbolic/issues/863
Fixes #860

feat(sourcebundle): Add callback to handle skipped files

---

.github/workflows/build.yml

Reverts getsentry/symbolic#858. `upload-artifacts` v4 is causing our release builds to fail as it is incompatible with our release build process.
We needed to [revert this change in Sentry CLI](https://github.com/getsentry/sentry-cli/pull/2119) for the same reason.

Revert "all-repos: update actions/upload-artifact to v4"

---

CHANGELOG.md
Cargo.lock
Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/base.rs
symbolic-debuginfo/src/dwarf.rs
symbolic-debuginfo/tests/snapshots/test_objects__elf_symbols.snap
symbolic-debuginfo/tests/snapshots/test_objects__pdb_symbols.snap
symbolic-symcache/tests/snapshots/test_writer__functions_linux.snap

We're using an unstable sorting algorithm (dmsort) to sort symbols upon collection. It behaves differently under Rust 1.81 than 1.80, so some snapshots change.

ref(debuginfo): Replace dmsort with std sort

---

CHANGELOG.md
symbolic-debuginfo/src/js.rs

Companion PR to https://github.com/getsentry/rust-sourcemap/pull/97. This adjusts `discover_sourcemap_embedded_debug_id` so that it finds debug IDs at both `"debug_id"` and `"debugId"`.
#skip-changelog because Danger is acting up.

feat(js): Read debug IDs from debugId field

---

CHANGELOG.md
symbolic-debuginfo/src/js.rs

Companion PR to https://github.com/getsentry/rust-sourcemap/pull/100.
Using a alias causes deserialization to fail when
both keys are set. Therefore we now read both fields and implement the logic explicitly.

fix(js): Resolve conflict between "debugId" and "debug_id"

---

CHANGELOG.md
symbolic-symcache/src/writer.rs

Addition wraps in release mode. For large line size values, this resulted in ranges whose end was before their start, which caused us to skip a function's inlinees in some cases.
Instead of using bare addition on `u64` and casting to `u32` at the end, we now use saturating addition on `u32` directly.

fix(symcache): Use saturating addition in writer

---

CHANGELOG.md
symbolic-demangle/build.rs

Older GCC versions do not have `-Wno-changes-meaning` as a separate warning, but it is part of the permissive category.
Also removes the mac os min, it's not actually required as I thought before it was.

fix(demangle): Suppresses c++ warnings on older GCCs

---

CHANGELOG.md
symbolic-demangle/build.rs

The `12.13.0` release and pull request #885 specifically broke GitHub Action based Windows builds. The reason seems to be that the Swift library upgrade now relies on C++17 features and the GitHub Actions Windows image uses MSVC 2022, which requires an explicit opt-in to those. The provided `-std=c++17` works on GCC and similar, but does not have any effect on MSVC.
To fix the build, add the flag that MSVC understands for opting in to the new standard.

fix(demangle): Unbreak GitHub Action Windows builds

---

CHANGELOG.md
Cargo.lock
Cargo.toml
symbolic-debuginfo/Cargo.toml
symbolic-debuginfo/src/sourcebundle/mod.rs
symbolic-debuginfo/src/sourcebundle/utf8_reader.rs

The current check to ensure a sourcebundle is valid UTF-8 reads the entire sourcebundle file into memory. This is inefficient for large files.
This PR introduces a UTF8Reader which wraps any reader. The UTF8Reader ensures that the stream is valid UTF8 as it is being read, while only requiring a small amount of memory (currently 8 KiB) to be allocated as a buffer.

ref(sourcebundle): Check UTF-8 validity memory efficiently

---

symbolic-common/src/path.rs
symbolic-debuginfo/src/macho/compact.rs
symbolic-debuginfo/src/wasm/parser.rs
symbolic-ppdb/src/format/metadata.rs
symbolic-ppdb/src/format/streams.rs

build: Fix Rust 1.85 clippy lints

---

CHANGELOG.md
Cargo.toml
README.md
symbolic-cfi/Cargo.toml
symbolic-common/Cargo.toml
symbolic-common/src/path.rs
symbolic-debuginfo/Cargo.toml
symbolic-demangle/Cargo.toml
symbolic-il2cpp/Cargo.toml
symbolic-ppdb/Cargo.toml
symbolic-symcache/Cargo.toml
symbolic-symcache/src/lookup.rs
symbolic-symcache/src/writer.rs
symbolic-unreal/Cargo.toml
symbolic/Cargo.toml

Fixes: #901
Request was for MSRV 1.75 but we can support 1.73 without any more changes.

build: pin MSRV to 1.73 and clarify policy

---

CHANGELOG.md
examples/minidump_stackwalk/src/main.rs

Currently using this to debug a minidump where I want some debug info loaded from the binary but others from system libraries.
The patch makes it possible to specify multiple sources.

feat(minidump-stackwalk): Allow specifying multiple sources

---

CHANGELOG.md
examples/minidump_stackwalk/src/main.rs

The instruction definitely belongs to this module, but we cannot
find the instruction. In which case this is most likely not a real
frame.
The minidump stackwalker skips alls frames without a name and continues
the search, but it assumes there is a correct frame if the lookup
fails. To not hallucinate frames, we return `Ok(())` here (a frame without a name).
Rust minidump code here: https://github.com/rust-minidump/rust-minidump/blob/32e01a0e54d987025aa64486ebc4154f7f6b16d2/minidump-unwind/src/lib.rs#L865-L877
Relates to: https://github.com/getsentry/sentry/issues/85336
With the change:
```
0  CrashApp.pdb!DoCrash(int, int) [CrashApp\CrashingProgram.cpp : 17]
rax = 0x0000000000000000      rdx = 0x0000000000000003
rcx = 0x00007ff7f3ad711d      rbx = 0x0000000000000000
rsi = …
```

fix(minidump-stackwalk): Do not hallucinate frames when stackwalking

---

CHANGELOG.md
examples/unreal_engine_crash/src/main.rs

Make it possible to extract individual files from an unreal crash report via the commandline utility.

feat(unreal-engine-crash): Add extraction command to cli utility

---

CHANGELOG.md

Splits the changes into appropriate sections to give more context what the change does.

ref: split changelog in sections

---

.craft.yml

In the previous PR we removed the `--format=zip` parameter from the Makefile but forgot to update the `.craft.yml` which led to another failed publish run because it failed to find the artifact.
This PR fixes the regex so that it finds the new source artifact.
Old PR: https://github.com/getsentry/symbolic/pull/910
Failed publish: https://github.com/getsentry/publish/actions/runs/14380071441/job/40321532143

fix(craft): update craft to find .tar.gz archives

---

CHANGELOG.md
py/tests/test_crashprobe.py
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/test_writer.rs

As of #897 we explicitly insert the ends of functions and symbols into symcaches to reduce bogus mappings. While this worked correctly for functions, we introduced a bug in the case of symbols that resulted in symbols not being properly inserted into symcaches.
This fixes the bug by explicitly overwriting previously inserted "empty" mappings.
Fixes #914. Fixes SYMBOL-9.

fix(symcache): Overwrite "empty" mappings for symbols

---

README.md

Noticed a broken link to `symbolic-cabi`, so wanted to fix it up.

fix outdated link to symbolic-cabi in README.md

---

CHANGELOG.md
symbolic-demangle/vendor/swift/1-arguments.patch
symbolic-demangle/vendor/swift/lib/Demangling/Demangler.cpp

Fixes: #912
Smaller version of #913 which attempts to update the entire swift demangler, but runs into other issues. 
Removing the assert is fine, as upstream ended up removing it as well. This is the minimal fix to stop crashing on bad inputs. Eventually we'll want to update the swift sources.
Removed Upstream: https://github.com/swiftlang/swift/blob/ace5c20b12ef404ef4f169a5484c2ae8b981cfc3/lib/Demangling/Demangler.cpp#L3544-L3547

fix(swift): Remove unnecessary assert in swift demangler

---

symbolic-demangle/tests/test_swift.rs

Forgot to add it to #917, just a regression test, to catch the abort.

test(swift): Add regression test for swift demangler crash

---

CHANGELOG.md
py/symbolic/sourcemap.py
symbolic-cabi/include/symbolic.h
symbolic-cabi/src/sourcemap.rs

Currently only a few functions of the underlying lib (https://github.com/getsentry/rust-sourcemap) are exposed. 
In particular, there's currently no way to get the source code contents, but just the names can currently be retrieved.
This change adds support to expose the fn SourceMap::get_source_contents : https://github.com/getsentry/rust-sourcemap/blob/24a07e376a634c7823ada1b55326454ba7fc921d/src/types.rs#L787-L792

Expose SourceMapView.get_source_contents function

---

CHANGELOG.md
Cargo.lock
Cargo.toml
symbolic-sourcemapcache/src/lookup.rs

This doesn't do anything without https://github.com/getsentry/rust-sourcemap/pull/129, but is sound even without it.

fix(sourcemapcache): Don't return unmapped source locations

---

CHANGELOG.md
py/manylinux.sh
py/setup.py

Python 3.6 was removed from the image, and is not longer available. 
Switching to Python 3.11 for build releases.

build: switch to python3.11 for releases builds

---

CHANGELOG.md
symbolic-symcache/src/writer.rs
symbolic-symcache/tests/breakpad.rs

https://github.com/getsentry/symbolic/pull/897 introduced a bug where functions without line records wouldn't correctly overwrite the previous function's end marker. This PR fixes the bug and factors the logic out into a function.
Closes INGEST-472.

fix(symcache): Correctly insert functions without line records

---

CHANGELOG.md
symbolic-sourcemapcache/src/lookup.rs
symbolic-sourcemapcache/tests/integration.rs

Previously, when looking up a line and column, we would always return the token at or immediately before that position, even if it belonged to an earlier minified line. This is
1. wrong—tokens are only meant to extend to the end of a line.
2. inconsistent—this means that an unmapped line before any mapped line
would return no mapping, but an unmapped line after a mapped line
would.

fix(sourcemapcache): Tokens only extend to the end of the line

---

CHANGELOG.md
Cargo.lock
Cargo.toml
symbolic-debuginfo/src/dwarf.rs

This updates the `gimli` dependency to give us access to https://github.com/gimli-rs/gimli/pull/791, in which the address -2 is allowed as a tombstone address in some DWARF files sections. This lets us extract debug info from some DWARF files that we couldn't handle before.
ref: INGEST-451

fix(dwarf): Allow -2 as a tombstone address
